package com.smartbuilders.smartsales.ecommerceandroidapp.utils;

import com.smartbuilders.smartsales.ecommerceandroidapp.model.ProductBrand;

import java.util.ArrayList;

/**
 * Created by Alberto on 23/4/2016.
 */
public class UtilsBrands {

    private ArrayList<ProductBrand> productBrands;

    public ArrayList<ProductBrand> getActiveProductBrands(){
        return productBrands;
    }

    public UtilsBrands(){
        productBrands.add(new ProductBrand(1009557,"AT","MOLINOS"));
        productBrands.add(new ProductBrand(1009387,"A1","CALENTADORES ELECTRICOS Y A GA FANAINOX - FANAMETAL - CAVEGAS"));
        productBrands.add(new ProductBrand(1009388,"A2","ANGULOS DE HIERRO-LAMINADOS    ACEROS LAMINADOS"));
        productBrands.add(new ProductBrand(1009558,"A3","PLETINAS DE HIERRO"));
        productBrands.add(new ProductBrand(1009389,"A4","DEVCON DE VENEZUELA            PEGA DEVCON"));
        productBrands.add(new ProductBrand(1009390,"A5","ESPATULA LATONERO              ESPATULA LATONERO"));
        productBrands.add(new ProductBrand(1009559,"A6","COLA PARA RATONES"));
        productBrands.add(new ProductBrand(1009391,"A7","CELOVEN                        PAPEL TIRRO/CINTA"));
        productBrands.add(new ProductBrand(1009392,"A8","PESAS Y BALANZAS"));
        productBrands.add(new ProductBrand(1009560,"A9","PROMOCION HENKEL"));
        productBrands.add(new ProductBrand(1009561,"B2","PROMOCION COMBOS LIJAS 3M"));
        productBrands.add(new ProductBrand(1009562,"B3","LIJAS 3M"));
        productBrands.add(new ProductBrand(1009393,"B5","PALAS, CAVADORAS (MEINCA)      HERRAMIEMTAS DE ALBAÑILERIA Y JARDINERIA"));
        productBrands.add(new ProductBrand(1009394,"B7","EXTENSIONES MACA"));
        productBrands.add(new ProductBrand(1009565,"B9","BELLOTA"));
        productBrands.add(new ProductBrand(1009397,"CO","CARBONES CONINCA               CARBONES PARA EQUIPOS Y HERRAMIENTAS"));
        productBrands.add(new ProductBrand(1009567,"C4","PROMOCION TIRROS 3M"));
        productBrands.add(new ProductBrand(1009396,"C9","SOPORTE Y TUBOS DE CORTINAS    3/8=TAURO.LOS DEMAS A SUFEIN"));
        productBrands.add(new ProductBrand(1009399,"D2","TUBOS CORRUGADOS PARA ELECTRID TUBOFLEX -TEC MONTE BLAN PROIMMEC."));
        productBrands.add(new ProductBrand(1009400,"D5","CALENTADORES DUCHA             TIMBRES"));
        productBrands.add(new ProductBrand(1009401,"D6","MECATE ELEFANTE CORDELERIA OC MECATES"));
        productBrands.add(new ProductBrand(1009574,"D7","LAMINAS DE ZINC IMPORTADO"));
        productBrands.add(new ProductBrand(1009575,"D8","LAMINAS DE ALUMINIO INDALVEN"));
        productBrands.add(new ProductBrand(1009402,"D9","ACCESORIOS PARA CERCAS         BRAZOS P/CERCAS BRAZO P/CERCA-BOLA PASANTE"));
        productBrands.add(new ProductBrand(1009403,"E2","PLOMO PARA PESCA               PLODECA"));
        productBrands.add(new ProductBrand(1009404,"E4","CARTON CHAPAFORTE              PROPULSO - CIMCA"));
        productBrands.add(new ProductBrand(1009405,"E9","BOMBA MANUAL Y ACCESORIOS      BOMBA P/AGUA ANDINA - EMPACADURA P/BOMBA"));
        productBrands.add(new ProductBrand(1009580,"FC","CARRETILLAS Y RUEDAS IMSA"));
        productBrands.add(new ProductBrand(1009406,"F1","LANA DE ACERO BONBRIL          LANA DE ACERO-PULEX NO.1"));
        productBrands.add(new ProductBrand(1009581,"F2","ZUNCHOS"));
        productBrands.add(new ProductBrand(1009407,"F3","PLETINAS - VARILLAS-ESTANTILLO MALLAS, CABILLAS, VIGAS, ESTANTILLOS Y PLETINAS"));
        productBrands.add(new ProductBrand(1009582,"F4","PLETINAS DE HIERRO PERFORADAS"));
        productBrands.add(new ProductBrand(1009583,"F5","CERCHAS P/CONSTRUCCION"));
        productBrands.add(new ProductBrand(1009408,"F6","ELECTRODOS  Y ALAMBRES AM Y AG ELECTRODOS"));
        productBrands.add(new ProductBrand(1009584,"F7","VARILLAS TREXA"));
        productBrands.add(new ProductBrand(1009585,"F8","VARILLAS FORJADOS TINAQUILLO"));
        productBrands.add(new ProductBrand(1009409,"F9","CURVAS  EMT PLASTICAS Y GALVAN TALLER IND HNOS GARGANO MACOPLAST INPLAVEN."));
        productBrands.add(new ProductBrand(1009412,"GR","LADRON DE AGUA                 REDIFER - GOALCA- DISTRIBUIDORA VANCOMI"));
        productBrands.add(new ProductBrand(1009410,"G1","PROMOCION ALTO INV G1"));
        productBrands.add(new ProductBrand(1009586,"G2","PROMOCION ALTO INV G2"));
        productBrands.add(new ProductBrand(1009587,"G3","PROMOCION ALTO INV G3"));
        productBrands.add(new ProductBrand(1009590,"G6","PROMOCION ALTO INV G6"));
        productBrands.add(new ProductBrand(1009591,"G7","Grupo 7"));
        productBrands.add(new ProductBrand(1009411,"G9","PROMOCION ALTO INV G9"));
        productBrands.add(new ProductBrand(1009932,"SQ","SPRAY QUIMICA"));
        productBrands.add(new ProductBrand(1009413,"VN","KIT DE FIBRA ECONOMICO         KIT DE FIBRA DE VIDRIO ECONOMICO"));
        productBrands.add(new ProductBrand(1009342,"01","ESCALERAS   DE ALUMINIO         ESCALERAS ALUMINIO"));
        productBrands.add(new ProductBrand(1009343,"02","CARBORUNDUM                    DISCOS CORTE Y RUEDA ESMERIL"));
        productBrands.add(new ProductBrand(1009344,"08","CABOS PARA HERRAMIENTAS AGRICO"));
        productBrands.add(new ProductBrand(1009345,"09","BELLOTA HERRAMIENTAS"));
        productBrands.add(new ProductBrand(1009347,"11","CEBRA                          BROCHAS CERDA PARA PINTAR"));
        productBrands.add(new ProductBrand(1009915,"12","BYD TALAD-LIJAD-SIERRAS-MECHA"));
        productBrands.add(new ProductBrand(1009348,"14","ALCAVE, CABLECO.              ALCAVE"));
        productBrands.add(new ProductBrand(1009601,"15","TOBOS Y PALUSTRAS PARA ALBAÑIL"));
        productBrands.add(new ProductBrand(1009602,"17","TOBOS PARA ALBAÑIL"));
        productBrands.add(new ProductBrand(1009349,"18","FUNDICION PACIFICO (VALVULAS / LLAVES MANGUERAS, BOLAS, COMPUERTA"));
        productBrands.add(new ProductBrand(1009350,"19","MACHETES VARIOS"));
        productBrands.add(new ProductBrand(1009351,"20","HENKEL VENEZOLANA              SELLADOR-METYLAN-SILICON-TEFLON LIQ.-TANGIT."));
        productBrands.add(new ProductBrand(1009603,"21","INVER-EXPO 21"));
        productBrands.add(new ProductBrand(1009352,"24","CANDADOS Y CERRADURAS CISA     INCETA DIST. FINCISA FANCA."));
        productBrands.add(new ProductBrand(1009353,"29","PIE DE AMIGO, COFRES           IND. LAMNA"));
        productBrands.add(new ProductBrand(1009354,"30","PRODUCTOS ASFALTICOS IPA       PRODUCTOS ASFALTICOS"));
        productBrands.add(new ProductBrand(1009355,"32","GANCHOS PARA TECHO             SALIM-IND. PRETOR"));
        productBrands.add(new ProductBrand(1009356,"33","HERRAJE, CANILLA, SURTID., DES MANG. LAV- W.C-HERRAJES- SURTIDORES"));
        productBrands.add(new ProductBrand(1009357,"37","CONEXIONES DE AGUAS BLANCAS"));
        productBrands.add(new ProductBrand(1009358,"38","CANILLAS, DUCHAS TELEFONOS     MANGUERAS P/LAVAMANO - W-C."));
        productBrands.add(new ProductBrand(1009359,"41","MANGUERAS CULEBRA/RIEGO/GAS    MANGUERA PLASTICA"));
        productBrands.add(new ProductBrand(1009360,"45","BOYAS, REGADERAS,BATEAS, GABIN DESAGUES-SIFONES-LAVAMANOS-W.C.-HERRAJES"));
        productBrands.add(new ProductBrand(1009361,"46","DRIZAS                         DRIZAS DE NYLON"));
        productBrands.add(new ProductBrand(1009362,"47","PALIN MINERO VARIOS            PALAS - CARRETILLAS"));
        productBrands.add(new ProductBrand(1009363,"49","NIPLES GALVANIZADOS            NIPLES GALVANIZADOS Y BARRAS ROSCADAS"));
        productBrands.add(new ProductBrand(1009364,"52","ACEITE PARA ROSCA EL PLOMERITO  ACEITE P/ROSCAS"));
        productBrands.add(new ProductBrand(1009365,"54","INODOR. REJILL. ANILL. CONECT. INODOROS Y REJILLAS"));
        productBrands.add(new ProductBrand(1009367,"60","MANILLAS                       CERRAJERIA PORTUGUESA, DIARCO"));
        productBrands.add(new ProductBrand(1009368,"61","DESAGUES, SIFONES, EXTENSIONES SIFONES Y EXTENSIONES DE METAL"));
        productBrands.add(new ProductBrand(1009625,"62","FERTUCA,C.A."));
        productBrands.add(new ProductBrand(1009369,"65","SOLDIMIX DE VNZLA.             PEGA SOLDIMIX"));
        productBrands.add(new ProductBrand(1009370,"66","CADENAS GALVANIZADAS           CADENAS GALVANIZADAS"));
        productBrands.add(new ProductBrand(1009371,"67","VARILLAS DE BRONCE Y HIERRO -  VARILLAS PARA SOLDAR Y PLOMO"));
        productBrands.add(new ProductBrand(1009629,"69","CONEXIONES GALVANIZADAS"));
        productBrands.add(new ProductBrand(1009372,"70","ESQUINEROS DE MALLAS CONSTRUCC ESQUINEROS"));
        productBrands.add(new ProductBrand(1009630,"71","CONEXIONES GALVANIZADAS BAMERI"));
        productBrands.add(new ProductBrand(1009373,"76","SPRAY QUIMICA                  SILICONE ABRILLANTADOR- AZUL PRUSIA"));
        productBrands.add(new ProductBrand(1009635,"77","TUBOS EMT GALVANIZADOS"));
        productBrands.add(new ProductBrand(1009374,"78","TUBOS DE CERCA Y HIERRO PULIDO IND. UNICON- ACEROS LAMINADOS- TUBOS ARMCO."));
        productBrands.add(new ProductBrand(1009375,"79","TUBOS  GALVANIZADOS PARA AGUAS C.A. CONDUVEN - IND MET REX"));
        productBrands.add(new ProductBrand(1009376,"80","3M                             PAPEL LIJA - UNDERSHEAL - PAPEL TIRRO"));
        productBrands.add(new ProductBrand(1009377,"81","UNITOP                         REMACHES UNITOP"));
        productBrands.add(new ProductBrand(1009378,"82","TUBOS PARA AGUAS BLANCAS       ARM TUBOS MANUFACT SPES VENTUPLAST."));
        productBrands.add(new ProductBrand(1009379,"83","CHAMPION( PINTURA EN SPRAY SAP PINTURA SPRAY-ESMALTE CHAMPION-REMOVEDOR"));
        productBrands.add(new ProductBrand(1009380,"84","RUEDA NEU/MAC P/CARRETILL"));
        productBrands.add(new ProductBrand(1009381,"86","PALUSTRAS TAURO                INDUSTRIAS TAURO SUMIN FERRET. INCA REP FERRBON"));
        productBrands.add(new ProductBrand(1009382,"88","FLEJES PARA PISO               INPLAVEN"));
        productBrands.add(new ProductBrand(1009383,"90","VICSON                         CLAVOS,MALLA VICCLON,ALAMBRE LISO"));
        productBrands.add(new ProductBrand(1009384,"91","alambres y mallas"));
        productBrands.add(new ProductBrand(1009385,"94","CAVAS-TERMOS-BOTELLONES"));
        productBrands.add(new ProductBrand(1009386,"98","SOPLETES"));
        productBrands.add(new ProductBrand(1011739,"gd0","GDM"));
        productBrands.add(new ProductBrand(1019662,"ke0","KEYTON ELECTRODOMESTICOS"));
        productBrands.add(new ProductBrand(1010404,"ov0","OVE"));
        productBrands.add(new ProductBrand(1011934,"si0","SICA"));
        productBrands.add(new ProductBrand(1009649,"A","EXTREME GLUE"));
        productBrands.add(new ProductBrand(1022926,"AAL","ALCAVE"));
        productBrands.add(new ProductBrand(1020166,"AAU","ACCESORIOS PARA CARRO"));
        productBrands.add(new ProductBrand(1010047,"AA1","CALENTADORES CAVEGAS"));
        productBrands.add(new ProductBrand(1019764,"ABN","ABN"));
        productBrands.add(new ProductBrand(1021282,"ABO","ABO"));
        productBrands.add(new ProductBrand(1029330,"ABT","ABT "));
        productBrands.add(new ProductBrand(1009951,"ACC","ACCESORIOS PARA BAÑOS CERAMICA"));
        productBrands.add(new ProductBrand(1009437,"ACE","TRAMPAS PARA RATON             TRAMPAS P/RATONES NACIONALES E IMPORTADAS"));
        productBrands.add(new ProductBrand(1019661,"ACO","AMCO"));
        productBrands.add(new ProductBrand(1016094,"ACS","ACESA"));
        productBrands.add(new ProductBrand(1010045,"AC1","ACCES BAÑO PLAST CROMADO"));
        productBrands.add(new ProductBrand(1010046,"AC2","ACCES BAÑO METALICO"));
        productBrands.add(new ProductBrand(1009549,"AC3","GIOLITO"));
        productBrands.add(new ProductBrand(1009568,"AC5","TAMAYO"));
        productBrands.add(new ProductBrand(1022097,"AFI","AFI"));
        productBrands.add(new ProductBrand(1010026,"AGU","MANILLAS IND AGUEDA"));
        productBrands.add(new ProductBrand(1029535,"AGZ","AGZ"));
        productBrands.add(new ProductBrand(1018955,"AIP","AIP"));
        productBrands.add(new ProductBrand(1009438,"AIR","PLASTICOS CON BURBUJAS         PLASTICO PROTECTOR BURBUJAS ( ENVOLTORIOS )"));
        productBrands.add(new ProductBrand(1012041,"AJH","AJH"));
        productBrands.add(new ProductBrand(1010030,"AKU","AKUASANA"));
        productBrands.add(new ProductBrand(1009439,"ALA","MALLAS ELECTROSOLDADAS         MALLAS TIPO ALASSO"));
        productBrands.add(new ProductBrand(1009440,"ALC","ALCAYATAS PARA HAMACA          MANUFACTURAS EL SANTO"));
        productBrands.add(new ProductBrand(1010097,"ALD","ALADINO"));
        productBrands.add(new ProductBrand(1009974,"ALF","ALFACOCINA"));
        productBrands.add(new ProductBrand(1029532,"ALG","ALG"));
        productBrands.add(new ProductBrand(1029533,"ALG","ALG"));
        productBrands.add(new ProductBrand(1009620,"ALJ","53"));
        productBrands.add(new ProductBrand(1009939,"ALK","CONCERTINAS"));
        productBrands.add(new ProductBrand(1012044,"ALM","ALM"));
        productBrands.add(new ProductBrand(1009987,"ALR","MANGUERA CUL ALROM"));
        productBrands.add(new ProductBrand(1023031,"ALS","ALS"));
        productBrands.add(new ProductBrand(1022316,"ALU","CONDUCTORES DE ALUCOBRE"));
        productBrands.add(new ProductBrand(1009441,"AMA","AMARRE DE ALAMBRE C-PLOMO      AMARRES CON PLOMO"));
        productBrands.add(new ProductBrand(1017825,"AMC","AMC"));
        productBrands.add(new ProductBrand(1023743,"AMG","AMG"));
        productBrands.add(new ProductBrand(1025589,"AMX","AMX"));
        productBrands.add(new ProductBrand(1010049,"AN","ANASIL"));
        productBrands.add(new ProductBrand(1009652,"ANA","ANASIL SILICONE"));
        productBrands.add(new ProductBrand(1009442,"ANC","ALCAYATAS DECORATIVAS PARA HAM"));
        productBrands.add(new ProductBrand(1019457,"AND","FERRE ANDINA"));
        productBrands.add(new ProductBrand(1009850,"APC","REGLETA APC"));
        productBrands.add(new ProductBrand(1014667,"AQM","HIDRONEUMATICOS AQUATIME"));
        productBrands.add(new ProductBrand(1009962,"AQT","PEDROLLO"));
        productBrands.add(new ProductBrand(1009443,"ARA","ARANDELAS Y TUERCAS            ARANDELAS Y TUERCAS"));
        productBrands.add(new ProductBrand(1021284,"ARI","ARI"));
        productBrands.add(new ProductBrand(1019054,"ART","ART"));
        productBrands.add(new ProductBrand(1020879,"ARV","ARV"));
        productBrands.add(new ProductBrand(1010146,"AST","MAYOR ASTRO"));
        productBrands.add(new ProductBrand(1009444,"ATC","IRWIN - VISEGRIP               ALICATES."));
        productBrands.add(new ProductBrand(1013554,"ATL","ATLAS GLOBAL"));
        productBrands.add(new ProductBrand(1021892,"ATO","ATO"));
        productBrands.add(new ProductBrand(1010031,"ATP","PROMOCION ALICATES"));
        productBrands.add(new ProductBrand(1018029,"ATR","ATR"));
        productBrands.add(new ProductBrand(1018028,"AT0","ATRIUM CA"));
        productBrands.add(new ProductBrand(1009831,"AUT","CERAMICAS AUTANA"));
        productBrands.add(new ProductBrand(1010044,"AVT","AVTEK"));
        productBrands.add(new ProductBrand(1020881,"A01","A01"));
        productBrands.add(new ProductBrand(1009435,"A10","RAYOVAC                        PILAS RAYOVAC"));
        productBrands.add(new ProductBrand(1009436,"A11","FREGADEROS DE ACERO Y ALUMINIO FANAINOX C.A"));
        productBrands.add(new ProductBrand(1009931,"A13","HIDROLAV AQUA13"));
        productBrands.add(new ProductBrand(1009989,"B&D","CANDADOS Y CERRADURAS B&D"));
        productBrands.add(new ProductBrand(1029953,"BAG","BALGRES"));
        productBrands.add(new ProductBrand(1009868,"BAL","ALFA COCINA"));
        productBrands.add(new ProductBrand(1009824,"BAM","BAMERICA"));
        productBrands.add(new ProductBrand(1010009,"BAN","PUERTAS PLEGABLES"));
        productBrands.add(new ProductBrand(1010139,"BAZ","SALAS BAHÍA AZUL"));
        productBrands.add(new ProductBrand(1009849,"BCH","BOSCH"));
        productBrands.add(new ProductBrand(1010003,"BDC","BLACK AND DECKER CANDADOS"));
        productBrands.add(new ProductBrand(1009977,"BDM","BLACK&DECKER MANUAL"));
        productBrands.add(new ProductBrand(1010133,"BD1","BLACK AND DECKER G1"));
        productBrands.add(new ProductBrand(1009990,"BD6","CERRADURAS Y CANDADOS BLACK AND DECKER"));
        productBrands.add(new ProductBrand(1013956,"BEG","BEG"));
        productBrands.add(new ProductBrand(1012954,"BEI","BEIBEI"));
        productBrands.add(new ProductBrand(1009445,"BEL","BELL POWER   PEGAMENTOS        PEGAMENTOS"));
        productBrands.add(new ProductBrand(1010128,"BEN","BENYCAR"));
        productBrands.add(new ProductBrand(1009446,"BES","BEST VALUE "));
        productBrands.add(new ProductBrand(1018341,"BEX","BEX"));
        productBrands.add(new ProductBrand(1009900,"BE1","PROMO ALICATES BELLOTA"));
        productBrands.add(new ProductBrand(1009898,"BE2","PROMO LIMAS BELLOTA"));
        productBrands.add(new ProductBrand(1009899,"BE3","BELL POWER TEMP"));
        productBrands.add(new ProductBrand(1022414,"BIC","BIC"));
        productBrands.add(new ProductBrand(1009447,"BIL","CABLES COAXIAL, CORNETA, TDI.   CABLES Y BOMBILLOS"));
        productBrands.add(new ProductBrand(1010025,"BIS","BISAGRAS"));
        productBrands.add(new ProductBrand(1009965,"BIT","BITUPLAST"));
        productBrands.add(new ProductBrand(1009857,"BJA","BAJA ROTACION"));
        productBrands.add(new ProductBrand(1011327,"BLU","BLUE LIGHTING"));
        productBrands.add(new ProductBrand(1018027,"BLY","BLY"));
        productBrands.add(new ProductBrand(1009814,"BM","BOUMAC"));
        productBrands.add(new ProductBrand(1023641,"BMA","PRODUCTOS BOSSMAN"));
        productBrands.add(new ProductBrand(1010062,"BMI","BM IDEAL"));
        productBrands.add(new ProductBrand(1029221,"BNK","BNK"));
        productBrands.add(new ProductBrand(1009659,"BOM","PROTONIC"));
        productBrands.add(new ProductBrand(1009811,"BON","LANA DE ACERO 200 GR"));
        productBrands.add(new ProductBrand(1023441,"BOO","BOO"));
        productBrands.add(new ProductBrand(1010093,"BO1","BOTAS PLASTICAS TOP"));
        productBrands.add(new ProductBrand(1010094,"BO2","BOTAS DE SEGURIDAD GSF"));
        productBrands.add(new ProductBrand(1026816,"BO3","BOTAS DE SEGURIDAD SFB"));
        productBrands.add(new ProductBrand(1026817,"BO4","BOTAS DE SEGURIDAD RHINO"));
        productBrands.add(new ProductBrand(1026818,"BO5","PANTALONES Y BOTINES SAFETY"));
        productBrands.add(new ProductBrand(1009448,"BRA","ABRAZADERAS, PARABICHOS        ABRAZADERAS Y PARABICHOS"));
        productBrands.add(new ProductBrand(1010086,"BRI","BRICOPRO"));
        productBrands.add(new ProductBrand(1009960,"BRK","BREAKERS Y TABLEROS BTICINO"));
        productBrands.add(new ProductBrand(1010095,"BRU","BRUDER GRUPO 8"));
        productBrands.add(new ProductBrand(1010116,"BR5","BRUDER GRUPO 5"));
        productBrands.add(new ProductBrand(1009964,"BSI","BSI"));
        productBrands.add(new ProductBrand(1026813,"BS1","BOTAS PLASTICAS"));
        productBrands.add(new ProductBrand(1009449,"BT0","LINEA INTERLINK TICINO"));
        productBrands.add(new ProductBrand(1009450,"BT1","LINEA COMPLEMENTARIA BTICINO"));
        productBrands.add(new ProductBrand(1009451,"BT2","LINEA MODUS PLUS BTICINO"));
        productBrands.add(new ProductBrand(1009452,"BT4","LINEA MODUS STYLE BTICINO"));
        productBrands.add(new ProductBrand(1009453,"BT5","LINEA MATIX BTICINO"));
        productBrands.add(new ProductBrand(1009454,"BT6","LINEA DOMINO DAVANT BTICINO"));
        productBrands.add(new ProductBrand(1009455,"BT7","PROMOCION TICINO"));
        productBrands.add(new ProductBrand(1009456,"BT8","OTROS TICINO"));
        productBrands.add(new ProductBrand(1010144,"BUF","FREGADEROS BUFFALO"));
        productBrands.add(new ProductBrand(1010050,"BUY","BUY LONG"));
        productBrands.add(new ProductBrand(1010078,"BVA","BEST VALUE AGRICOLA"));
        productBrands.add(new ProductBrand(1010038,"BVC","BARRAS AJUSTABLES"));
        productBrands.add(new ProductBrand(1009972,"BV1","BEST VALUE PROMO G1"));
        productBrands.add(new ProductBrand(1009855,"BV6","BEST VALUE G06"));
        productBrands.add(new ProductBrand(1010010,"BW","CABLE"));
        productBrands.add(new ProductBrand(1009654,"BYD","BLACK AND DECKER"));
        productBrands.add(new ProductBrand(1009457,"BZO","BUZONES                        BUZONES"));
        productBrands.add(new ProductBrand(1009548,"B06","ARRIGO"));
        productBrands.add(new ProductBrand(1010132,"B09","BELLOTA G1"));
        productBrands.add(new ProductBrand(1009660,"B10","CADENAS PARA MATEROS"));
        productBrands.add(new ProductBrand(1009661,"CAB","CABLESCA"));
        productBrands.add(new ProductBrand(1009662,"CAD","CADENAS, ESLABONES Y MOSQUETON"));
        productBrands.add(new ProductBrand(1029327,"CAL","CAL "));
        productBrands.add(new ProductBrand(1009550,"CAM","CA MEJIA"));
        productBrands.add(new ProductBrand(1011330,"CAP","CAPRINO"));
        productBrands.add(new ProductBrand(1009982,"CAR","CARNU"));
        productBrands.add(new ProductBrand(1009918,"CAT","ELECTRICO"));
        productBrands.add(new ProductBrand(1009904,"CA1","CA MEJIAS/ SUPLIDORA GIFELCA"));
        productBrands.add(new ProductBrand(1009944,"CBC","COBERCARGO"));
        productBrands.add(new ProductBrand(1010053,"CBO","COMBOS VARIOS"));
        productBrands.add(new ProductBrand(1009963,"CBV","COMBOS BEST VALUE"));
        productBrands.add(new ProductBrand(1009878,"CEB","CEBRA"));
        productBrands.add(new ProductBrand(1009950,"CED","MALLAS CEDAZO"));
        productBrands.add(new ProductBrand(1009458,"CEN","ACCESORIOS PINTAR GOMA ESPUMA  ACCESORIOS PINTURA"));
        productBrands.add(new ProductBrand(1010714,"CER","CERCHAS GENERICAS"));
        productBrands.add(new ProductBrand(1009664,"CHA","UNITED CHEMICAL PACKAGING, C.A. "));
        productBrands.add(new ProductBrand(1009551,"CHR","CHARGER   FILTROS              FILTROS Y CARTCHOS PARA FILTROS"));
        productBrands.add(new ProductBrand(1021686,"CH2","CH2"));
        productBrands.add(new ProductBrand(1010127,"CIE","CIERRE EJERCICIO"));
        productBrands.add(new ProductBrand(1010027,"CIL","PROTECTOR DE CILINDROS"));
        productBrands.add(new ProductBrand(1009936,"CIM","CIMAPRO, C.A."));
        productBrands.add(new ProductBrand(1009459,"CIN","CINTAS KALUCA"));
        productBrands.add(new ProductBrand(1009865,"CIS","CENTO DE INFORMACION"));
        productBrands.add(new ProductBrand(1009843,"CLA","CORPORACION LINEA AZUL"));
        productBrands.add(new ProductBrand(1028062,"CLD","CLD"));
        productBrands.add(new ProductBrand(1009820,"CLE","CLAVOS EMPACADOS"));
        productBrands.add(new ProductBrand(1009819,"CLG","CLAVOS GRANEL"));
        productBrands.add(new ProductBrand(1009905,"CLO","CLOROX "));
        productBrands.add(new ProductBrand(1010079,"CLS","MUEBLES CASA LISTA"));
        productBrands.add(new ProductBrand(1025182,"CL1","CL1"));
        productBrands.add(new ProductBrand(1010056,"CMD","COMMMANDER"));
        productBrands.add(new ProductBrand(1009460,"CMR","KIT DE ORINGS                  CORPORACION MIL REPUESTOS, C.A."));
        productBrands.add(new ProductBrand(1026610,"CNC","CONINCA"));
        productBrands.add(new ProductBrand(1025078,"CNO","CNO"));
        productBrands.add(new ProductBrand(1009973,"CN1","PROMOCION CANDADOS"));
        productBrands.add(new ProductBrand(1009461,"COB","CONEXIONES PARA TUBERIA DE COB CONEXIONES DE BRONCE"));
        productBrands.add(new ProductBrand(1009462,"COC","COCINAS Y ACCESORIOS           COCINAS, REVERBEROS, REGULADORES ETC."));
        productBrands.add(new ProductBrand(1010060,"COD","CODIRE"));
        productBrands.add(new ProductBrand(1009463,"COE","PISTOLAS COMEC                 PISTOLAS DE PINTURAS"));
        productBrands.add(new ProductBrand(1021582,"COF","COFERSA"));
        productBrands.add(new ProductBrand(1012952,"COL","COLOSO"));
        productBrands.add(new ProductBrand(1009665,"COM","COMETA"));
        productBrands.add(new ProductBrand(1009464,"CON","CONEXIONES PLASTICAS PARA RIEG"));
        productBrands.add(new ProductBrand(1009465,"COO","CRESCENT                       CAUTIN- SOLDADORES."));
        productBrands.add(new ProductBrand(1009466,"COP","COOPERWELD"));
        productBrands.add(new ProductBrand(1009818,"COR","BOTA CAÑA CORTA"));
        productBrands.add(new ProductBrand(1010041,"COS","COSMOLAMP"));
        productBrands.add(new ProductBrand(1009943,"COV","COVESMAT "));
        productBrands.add(new ProductBrand(1028408,"CPV","CONVENIO COMERCIAL"));
        productBrands.add(new ProductBrand(1018235,"CRB","CRB"));
        productBrands.add(new ProductBrand(1025692,"CTP","CTP"));
        productBrands.add(new ProductBrand(1010088,"CUC","CUCH BELLOTA"));
        productBrands.add(new ProductBrand(1011229,"CVC","COVALCA"));
        productBrands.add(new ProductBrand(1010203,"CVO","COVO"));
        productBrands.add(new ProductBrand(1009467,"CY1","CAJETINES METAL. 2X4 Y OCTAGON JTAMAYO SUCESORES"));
        productBrands.add(new ProductBrand(1025484,"C10","CORTINEROS Y OTROS"));
        productBrands.add(new ProductBrand(1009667,"C11","MARCA C11"));
        productBrands.add(new ProductBrand(1010130,"DAM","MATERIALES ELECTRICOS"));
        productBrands.add(new ProductBrand(1009847,"DAU","DAUER"));
        productBrands.add(new ProductBrand(1020471,"DCF","DECOFLOOR"));
        productBrands.add(new ProductBrand(1013354,"DCM","DCM"));
        productBrands.add(new ProductBrand(1009398,"DD1","TUBERIA  DE COBRE"));
        productBrands.add(new ProductBrand(1010008,"DEC","DECA"));
        productBrands.add(new ProductBrand(1009468,"DEL","SHOPMASTER - DELTA             HERRAMIENTAS ELECTRICAS ESTACIONARIAS"));
        productBrands.add(new ProductBrand(1009815,"DER","DERIVADOS PLASTICOS"));
        productBrands.add(new ProductBrand(1009669,"DEW","HERRAMIENTAS DEWALT"));
        productBrands.add(new ProductBrand(1015781,"DE1","MECHAS DEWALT"));
        productBrands.add(new ProductBrand(1027644,"DFM","DFM"));
        productBrands.add(new ProductBrand(1020775,"DIF","DIF"));
        productBrands.add(new ProductBrand(1014058,"DIM","DIM"));
        productBrands.add(new ProductBrand(1009670,"DIS","DISORCA"));
        productBrands.add(new ProductBrand(1009910,"DKP","DIST.EL KIT DEL PINTOR"));
        productBrands.add(new ProductBrand(1013151,"DLT","GENERADORES"));
        productBrands.add(new ProductBrand(1010413,"DLX","DURALUX"));
        productBrands.add(new ProductBrand(1017312,"DML","DML"));
        productBrands.add(new ProductBrand(1024870,"DNO","DNO"));
        productBrands.add(new ProductBrand(1009469,"DOM","EQUIPOS DOMOSA                 BOMBAS, MOTOSIERRAS, CORTAGRAMA, GENERADORES"));
        productBrands.add(new ProductBrand(1029950,"DPF","DISPUFIL"));
        productBrands.add(new ProductBrand(1010059,"DRA","DRACCO"));
        productBrands.add(new ProductBrand(1015578,"DRG","DRAGON"));
        productBrands.add(new ProductBrand(1010080,"DR1","DR.CARE"));
        productBrands.add(new ProductBrand(1009833,"DSC","DISCOS"));
        productBrands.add(new ProductBrand(1009912,"DSI","GRIFERIA WEQUP IMPORTADO"));
        productBrands.add(new ProductBrand(1009911,"DSN","GRIFERIA WEQUP NACIONAL"));
        productBrands.add(new ProductBrand(1028919,"DTP","DTP"));
        productBrands.add(new ProductBrand(1009830,"DUR","DURAMIL"));
        productBrands.add(new ProductBrand(1010032,"DW1","DEWALT MECHAS"));
        productBrands.add(new ProductBrand(1010129,"DW2","DISCOS DEWALT"));
        productBrands.add(new ProductBrand(1009471,"EAH","NICHOLSON - COLLINS            EMPRESA ANDINA DE HERRAMIENTAS"));
        productBrands.add(new ProductBrand(1021792,"ECL","ECL"));
        productBrands.add(new ProductBrand(1014167,"ECO","ECO"));
        productBrands.add(new ProductBrand(1009854,"EFC","VENEQUIRCA C.A."));
        productBrands.add(new ProductBrand(1028818,"EGR","EGR"));
        productBrands.add(new ProductBrand(1009472,"ELE","GLOBAL DAMCA"));
        productBrands.add(new ProductBrand(1009473,"ELI","PRODUCTOS A ELIMINAR           PRODUCTOS A ELIMINAR"));
        productBrands.add(new ProductBrand(1009474,"EMP","MALLAS MOSQUITERO PLASTICAS    MALLAS MOSQUITEROS"));
        productBrands.add(new ProductBrand(1010006,"EMS","TUBERIA EMT PREMIUN"));
        productBrands.add(new ProductBrand(1009475,"EMT","TUBOS DE ELECTRICIDAD GALVANIZ"));
        productBrands.add(new ProductBrand(1015375,"ENC","ENC"));
        productBrands.add(new ProductBrand(1018552,"ENG","ENG"));
        productBrands.add(new ProductBrand(1024766,"EPO","EPO"));
        productBrands.add(new ProductBrand(1009675,"ESA","TUBOS GALVANIZADOS CONDUPLAST"));
        productBrands.add(new ProductBrand(1009676,"ESQ","ESQUINEROS DE MALLA"));
        productBrands.add(new ProductBrand(1009476,"EUP","CONOS DE SEGURIDAD             CONOS DE SEGURIDAD"));
        productBrands.add(new ProductBrand(1017423,"EVO","EVO"));
        productBrands.add(new ProductBrand(1009860,"EXH","EXHIBIDORES"));
        productBrands.add(new ProductBrand(1010090,"EXP","INVER-EXPO RAMPLUG"));
        productBrands.add(new ProductBrand(1018033,"EXS","EXTINTORES"));
        productBrands.add(new ProductBrand(1009993,"EXT","PEGAMENTO EPOXICO"));
        productBrands.add(new ProductBrand(1010118,"E1","MUNICIONES EL TIGRE"));
        productBrands.add(new ProductBrand(1009470,"E11","RASTRILLOS"));
        productBrands.add(new ProductBrand(1009478,"FAD","RAMPLUG PLASTICOS EXPANSIBLES  RAMPLUG EXPANSIBLE PLATICOS"));
        productBrands.add(new ProductBrand(1009895,"FAE","FAESIN"));
        productBrands.add(new ProductBrand(1009986,"FC1","CARRUCHAS RUTEL"));
        productBrands.add(new ProductBrand(1010409,"FED","FEDERAL"));
        productBrands.add(new ProductBrand(1010066,"FEM","Corporación Korclass"));
        productBrands.add(new ProductBrand(1009886,"FER","FERMETAL"));
        productBrands.add(new ProductBrand(1009832,"FES","FESTER"));
        productBrands.add(new ProductBrand(1009927,"FG","FOREST & GARDEN (GBS)"));
        productBrands.add(new ProductBrand(1009940,"FG1","FOREST CORTAGRAMA"));
        productBrands.add(new ProductBrand(1010052,"FIB","FIBREFLEX"));
        productBrands.add(new ProductBrand(1010103,"FIL","MANGUERAS FIL-NOX"));
        productBrands.add(new ProductBrand(1010051,"FIO","FIORELLA"));
        productBrands.add(new ProductBrand(1015376,"FLE","FLE"));
        productBrands.add(new ProductBrand(1009858,"FLU","FLUIDMASTER"));
        productBrands.add(new ProductBrand(1025074,"FLX","FLX"));
        productBrands.add(new ProductBrand(1018446,"FMA","FMA"));
        productBrands.add(new ProductBrand(1010074,"FM0","FERMETAL 0"));
        productBrands.add(new ProductBrand(1010075,"FM1","FERMETAL 1"));
        productBrands.add(new ProductBrand(1010073,"FM3","FM POWERGRUPO 3"));
        productBrands.add(new ProductBrand(1010112,"FM5","FERMETAL GRUPO 5"));
        productBrands.add(new ProductBrand(1012753,"FM6","FM6"));
        productBrands.add(new ProductBrand(1010113,"FM8","FERMETAL GRUPO 8"));
        productBrands.add(new ProductBrand(1010147,"FOM","FORJAS ORN MCY"));
        productBrands.add(new ProductBrand(1009479,"FOR","COLLARES Y PECHERAS            COLLARES Y PECHERAS"));
        productBrands.add(new ProductBrand(1009480,"FOT","ARMELLAS                       INDUSTRIAS FORTINO"));
        productBrands.add(new ProductBrand(1022517,"FPO","FPO"));
        productBrands.add(new ProductBrand(1027440,"FRK","FRK"));
        productBrands.add(new ProductBrand(1010039,"FRR","FERRE EXPRESS"));
        productBrands.add(new ProductBrand(1028714,"FRY","FRY"));
        productBrands.add(new ProductBrand(1010048,"FUL","FULLER"));
        productBrands.add(new ProductBrand(1010123,"FV","FRANZ VIEGENER"));
        productBrands.add(new ProductBrand(1028512,"FYA","FYA"));
        productBrands.add(new ProductBrand(1009481,"FYM","FM POWER MATERIALES ELECTRICOS"));
        productBrands.add(new ProductBrand(1009477,"F10","LINCOLN                        ELECTRODOS Y SOLDADORAS"));
        productBrands.add(new ProductBrand(1009994,"F9A","CURVAS GALVANIZADAS"));
        productBrands.add(new ProductBrand(1010068,"G&E","GENERAL&ELECTRIC"));
        productBrands.add(new ProductBrand(1009679,"GAB","GABINETES CRUZ ROJAS"));
        productBrands.add(new ProductBrand(1009483,"GAR","GARGANO"));
        productBrands.add(new ProductBrand(1014061,"GBG","GBG"));
        productBrands.add(new ProductBrand(1009884,"GBS","FOREST & GARDEN/ LINCE"));
        productBrands.add(new ProductBrand(1011745,"GDA","GLD"));
        productBrands.add(new ProductBrand(1009842,"GEL","MANOMETROS,CARGADORES,PRESOSTA"));
        productBrands.add(new ProductBrand(1009484,"GEN","EXCELINE"));
        productBrands.add(new ProductBrand(1009880,"GEO","CERRADURAS B&D"));
        productBrands.add(new ProductBrand(1029539,"GGC","GGC"));
        productBrands.add(new ProductBrand(1010019,"GIO","CARMELU & GIO"));
        productBrands.add(new ProductBrand(1009983,"GLA","GLADE"));
        productBrands.add(new ProductBrand(1011743,"GLD","GD"));
        productBrands.add(new ProductBrand(1010084,"GLE","GENERAL & ELECTRIC"));
        productBrands.add(new ProductBrand(1009485,"GLO","WEQUP"));
        productBrands.add(new ProductBrand(1016099,"GLT","GELTECA"));
        productBrands.add(new ProductBrand(1014366,"GME","EMBUDO GMP"));
        productBrands.add(new ProductBrand(1010117,"GMO","GAMO"));
        productBrands.add(new ProductBrand(1009828,"GMP","GENERAL MODERN PLASTIC C.A."));
        productBrands.add(new ProductBrand(1022919,"GMS","GMS"));
        productBrands.add(new ProductBrand(1024658,"GNT","GENETRON"));
        productBrands.add(new ProductBrand(1009486,"GOO","GOODYEAR  MANGUERAS MULTIUSO"));
        productBrands.add(new ProductBrand(1009487,"GRA","SILIPEX SILICONES              PEGAMENTOS GRAFFITI"));
        productBrands.add(new ProductBrand(1022308,"GRF","GRF"));
        productBrands.add(new ProductBrand(1009959,"GRI","GRINACA"));
        productBrands.add(new ProductBrand(1009821,"GRP","GRAPAS"));
        productBrands.add(new ProductBrand(1010111,"GSF","GOOD SAFETY"));
        productBrands.add(new ProductBrand(1028410,"GSJ","GSJ"));
        productBrands.add(new ProductBrand(1009488,"GTO","CERRADURAS GATO                CERRADURAS"));
        productBrands.add(new ProductBrand(1009489,"GTR","CERRADURAS GATER               CERRADURAS Y CILINDROS IMPORTADOS"));
        productBrands.add(new ProductBrand(1029531,"GTT","GTT"));
        productBrands.add(new ProductBrand(1010028,"GT2","CERRADURAS GATER NACIONAL"));
        productBrands.add(new ProductBrand(1010065,"GUA","GUAROTAPA"));
        productBrands.add(new ProductBrand(1009978,"GUI","GUILLMOR"));
        productBrands.add(new ProductBrand(1010024,"GV7","ALCAYATAS"));
        productBrands.add(new ProductBrand(1009907,"G0","PROMOCION KONTIKI"));
        productBrands.add(new ProductBrand(1009482,"G10","PLASTICOS F.A.D"));
        productBrands.add(new ProductBrand(1009953,"G4","GRUPO 4"));
        productBrands.add(new ProductBrand(1009955,"G6","GRUPO 6"));
        productBrands.add(new ProductBrand(1009954,"G8","ALTO INVENTARIO G8"));
        productBrands.add(new ProductBrand(1009901,"G91","ZINC MARACUCHO"));
        productBrands.add(new ProductBrand(1009924,"G92","LAMINAS ALUMINIO"));
        productBrands.add(new ProductBrand(1027849,"HAL","HAL"));
        productBrands.add(new ProductBrand(1023338,"HEA","HEA LIGHT"));
        productBrands.add(new ProductBrand(1010110,"HEN","PROMO HENKEL"));
        productBrands.add(new ProductBrand(1009490,"HER","HERCULES"));
        productBrands.add(new ProductBrand(1009853,"HHR","HERRAGRO"));
        productBrands.add(new ProductBrand(1009840,"HID","HIDROCA"));
        productBrands.add(new ProductBrand(1010043,"HL","COMERCIALIZADORA HL"));
        productBrands.add(new ProductBrand(1018338,"HLP","HLP"));
        productBrands.add(new ProductBrand(1026303,"HMS","HMS"));
        productBrands.add(new ProductBrand(1022312,"HON","HON"));
        productBrands.add(new ProductBrand(1024871,"HRC","HRC"));
        productBrands.add(new ProductBrand(1009491,"HRI","PALUSTRAS BORDE CENTRAL/EXTERN"));
        productBrands.add(new ProductBrand(1025992,"HWL","HWL"));
        productBrands.add(new ProductBrand(1010408,"HYP","HYPO"));
        productBrands.add(new ProductBrand(1010109,"HYS","HYSTICK"));
        productBrands.add(new ProductBrand(1010042,"HYU","HYUNDAI"));
        productBrands.add(new ProductBrand(1009492,"IAC","CONEXIONES P/TANQUES PLASTICAS HIDRO PLASTICA, C.A"));
        productBrands.add(new ProductBrand(1013153,"IBE","IBE"));
        productBrands.add(new ProductBrand(1029324,"ICA","PROMO BOMBAS VARIAS"));
        productBrands.add(new ProductBrand(1023849,"ICE","ICE"));
        productBrands.add(new ProductBrand(1009817,"IEG","I.E GLOBALES (CERCO ELECTRICO)"));
        productBrands.add(new ProductBrand(1020777,"IKA","IKA"));
        productBrands.add(new ProductBrand(1014876,"ILV","ILV"));
        productBrands.add(new ProductBrand(1013857,"IMC","INVERSIONES MONACO"));
        productBrands.add(new ProductBrand(1013757,"IMD","IMD"));
        productBrands.add(new ProductBrand(1021382,"IMF","IMF"));
        productBrands.add(new ProductBrand(1009493,"IMP","PRODUCTOS IMPORTADOS DE NATURALEZA GENERICA"));
        productBrands.add(new ProductBrand(1010020,"IMS","PRODUCTOS IMSA CARRETILLAS"));
        productBrands.add(new ProductBrand(1021688,"IMV","INMEVENCA"));
        productBrands.add(new ProductBrand(1009494,"INA","INACO"));
        productBrands.add(new ProductBrand(1009495,"INC","MACHETES INCA-METAL"));
        productBrands.add(new ProductBrand(1010015,"IND","EL INDIO"));
        productBrands.add(new ProductBrand(1009966,"ING","INGCO"));
        productBrands.add(new ProductBrand(1014975,"INM","INM"));
        productBrands.add(new ProductBrand(1009689,"INV","INVERSIONES VERPLAST"));
        productBrands.add(new ProductBrand(1009496,"IRP","GOMAS (GRIFERIA / PLOMERIA, CU INDUSTRIAS RUBBER PLAST C.A."));
        productBrands.add(new ProductBrand(1021482,"IRW","IRW"));
        productBrands.add(new ProductBrand(1029537,"ISA","ISA"));
        productBrands.add(new ProductBrand(1015785,"ITA","ITALUM"));
        productBrands.add(new ProductBrand(1024556,"ITP","ITP"));
        productBrands.add(new ProductBrand(1009497,"IVI","IVICA"));
        productBrands.add(new ProductBrand(1009499,"JAR","RAMPLUG ESPAGUETI              RAMPLUG PLASTICO"));
        productBrands.add(new ProductBrand(1027028,"JAS","JAS"));
        productBrands.add(new ProductBrand(1009926,"JAZ","JAZ"));
        productBrands.add(new ProductBrand(1013454,"JIA","JIA"));
        productBrands.add(new ProductBrand(1028194,"JNO","JNO"));
        productBrands.add(new ProductBrand(1010087,"JOF","BISAGRAS Y MANILLAS JOFICRU"));
        productBrands.add(new ProductBrand(1028409,"JP2","JP2"));
        productBrands.add(new ProductBrand(1025385,"JUM","JUM"));
        productBrands.add(new ProductBrand(1009690,"J13","PULITURA BRASSO LIQUIDO"));
        productBrands.add(new ProductBrand(1009498,"J14","CREOLINA PERSON"));
        productBrands.add(new ProductBrand(1009991,"J15","ARCA"));
        productBrands.add(new ProductBrand(1028086,"KBX","ELECTRODOS KOBATEX"));
        productBrands.add(new ProductBrand(1014467,"KB0","KB0"));
        productBrands.add(new ProductBrand(1019663,"KEY"," KEYTON ELECTRODOMESTICOS"));
        productBrands.add(new ProductBrand(1029750,"KLA","KLA"));
        productBrands.add(new ProductBrand(1009500,"KOB","KOBY                           SOCATES, ENCHUFES, TOMAS Y LAMPARAS"));
        productBrands.add(new ProductBrand(1009501,"KON","BALASTOS ELECTRONICOS          STARTERS/BALASTOS/CABLE COAXIAL/ETC"));
        productBrands.add(new ProductBrand(1009502,"KOR","NYLON"));
        productBrands.add(new ProductBrand(1009979,"KOT","REPRESENTACIONES KONTIKI"));
        productBrands.add(new ProductBrand(1023240,"KPR","KPR"));
        productBrands.add(new ProductBrand(1010142,"KRO","INDUKROM"));
        productBrands.add(new ProductBrand(1009902,"KWI","POMO Y MANILLA B&D"));
        productBrands.add(new ProductBrand(1009933,"LAM","REJILLAS ACERO INOX. LAMNA"));
        productBrands.add(new ProductBrand(1010061,"LAP","LAMPONIX"));
        productBrands.add(new ProductBrand(1009503,"LAR","CORDELES Y GUARALES \"SISALARA\" SISALARA"));
        productBrands.add(new ProductBrand(1010077,"LBO","LINCE BOMBAS"));
        productBrands.add(new ProductBrand(1025081,"LCE","LCE"));
        productBrands.add(new ProductBrand(1009992,"LCH","PIEZAS HERRERIA"));
        productBrands.add(new ProductBrand(1010076,"LC1","LINCE G1"));
        productBrands.add(new ProductBrand(1009504,"LD1","LAMPARAS DECORATIVAS (PLAFON,  NUEVO SURTIDO LUMINARIAS"));
        productBrands.add(new ProductBrand(1015176,"LEV","LEV"));
        productBrands.add(new ProductBrand(1010018,"LIJ","LIJA LINCE PRO"));
        productBrands.add(new ProductBrand(1009816,"LIN","LINCOLN ELECTRIC"));
        productBrands.add(new ProductBrand(1009903,"LIQ","LIQUIDACION INVENTARIOL"));
        productBrands.add(new ProductBrand(1009967,"LI0","LINCOLN G0"));
        productBrands.add(new ProductBrand(1026097,"LJM","LJM"));
        productBrands.add(new ProductBrand(1009505,"LLU","CANALES Y ACCESORIOS DE PVC PA CANALES Y ACCESORIOS PARA LA LLUVIA"));
        productBrands.add(new ProductBrand(1025792,"LMC","LMC"));
        productBrands.add(new ProductBrand(1009929,"LNC","LINCE"));
        productBrands.add(new ProductBrand(1009971,"LNP","LINCE PROMOCION"));
        productBrands.add(new ProductBrand(1009925,"LOC","LOCOMOTIVA ENCERADOS"));
        productBrands.add(new ProductBrand(1010124,"LOF","LOFTIN"));
        productBrands.add(new ProductBrand(1019557,"LON","LON"));
        productBrands.add(new ProductBrand(1010089,"LOR","DUCHAS ELECTRICAS BIG SHOWER"));
        productBrands.add(new ProductBrand(1017823,"LPR","LA PALMA REAL"));
        productBrands.add(new ProductBrand(1010054,"LPX","LAMPARAS ONIX"));
        productBrands.add(new ProductBrand(1026197,"LSC","LSC"));
        productBrands.add(new ProductBrand(1009946,"LUC","LUCIANI"));
        productBrands.add(new ProductBrand(1009506,"LUM","LAMPARAS FLUORESCENTE C/ BALAS LUMICENTRO"));
        productBrands.add(new ProductBrand(1015776,"LUQ","LUQUE"));
        productBrands.add(new ProductBrand(1010040,"LUS","LUSO"));
        productBrands.add(new ProductBrand(1009507,"LUX","LUXVEN                         NIVELES-PALUSTRAS-PLOMADAS-ARCOS P/SEGUETAS"));
        productBrands.add(new ProductBrand(1025075,"MAB","MAB"));
        productBrands.add(new ProductBrand(1009508,"MAC","ALFOMBRAS ANTI RESBALENTES DE  ALFOMBRAS ANTI-RESBALANTES DE GOMA"));
        productBrands.add(new ProductBrand(1009834,"MAG","CORPORACION MAGITEL"));
        productBrands.add(new ProductBrand(1009509,"MAN","MANPICA C.A.                   MASTIQUE Y PASTA PROFESIONAL"));
        productBrands.add(new ProductBrand(1010004,"MAP","MANILLAS PARA PUERTAS"));
        productBrands.add(new ProductBrand(1009941,"MAS","ACCESORIOS P/PERRO"));
        productBrands.add(new ProductBrand(1009826,"MAT","CORPORACION MATLAND C.A."));
        productBrands.add(new ProductBrand(1011533,"MAU","ASPIRADORAS MAUTE"));
        productBrands.add(new ProductBrand(1009510,"MAV","CARRUCHAS Y RUEDAS \"RUTEL\"     CARRUCHAS - RUEDAS"));
        productBrands.add(new ProductBrand(1022929,"MAZ","MAZ"));
        productBrands.add(new ProductBrand(1009921,"MB","MB"));
        productBrands.add(new ProductBrand(1010085,"MBE","BELL POWER CULEBRA"));
        productBrands.add(new ProductBrand(1009919,"MCH","MACHETES"));
        productBrands.add(new ProductBrand(1015790,"MCI","MULTIPALUSTRA MC INDUSTRIALES"));
        productBrands.add(new ProductBrand(1009937,"MCL","MANGUERAS CULEBRAS"));
        productBrands.add(new ProductBrand(1026302,"MCM","MCM"));
        productBrands.add(new ProductBrand(1010063,"MDK","MADERKA"));
        productBrands.add(new ProductBrand(1011332,"MDS","MATERIALES ELECTRICOS HYUNDAI"));
        productBrands.add(new ProductBrand(1009511,"MED","CAJAS Y TABLEROS P/MEDIDOR     TABLEROS RESID,CJA MEDIDOR,CJA DE PASO"));
        productBrands.add(new ProductBrand(1009988,"MEI","MACHETE EL INDIO"));
        productBrands.add(new ProductBrand(1026713,"MEM","MEM"));
        productBrands.add(new ProductBrand(1022301,"MER","MERCURION"));
        productBrands.add(new ProductBrand(1009839,"MET","METALES ALEADOS"));
        productBrands.add(new ProductBrand(1028716,"MGY","MGY"));
        productBrands.add(new ProductBrand(1028081,"MG1","MANGUERAS CONTITECH"));
        productBrands.add(new ProductBrand(1010115,"MHF","TUBO METALICO CORRUGADO IMPORTADO"));
        productBrands.add(new ProductBrand(1016706,"MIR","MIR"));
        productBrands.add(new ProductBrand(1011328,"MIU","MIURA"));
        productBrands.add(new ProductBrand(1009984,"MKJ","MKJOULES"));
        productBrands.add(new ProductBrand(1014671,"MOA","MOA"));
        productBrands.add(new ProductBrand(1012346,"MON","MONOLENTE"));
        productBrands.add(new ProductBrand(1009980,"MOT","MOTINDUSTRIA"));
        productBrands.add(new ProductBrand(1024153,"MPL","MANAPLAS"));
        productBrands.add(new ProductBrand(1024255,"MQZ","MQZ"));
        productBrands.add(new ProductBrand(1021083,"MRP","MRP"));
        productBrands.add(new ProductBrand(1026407,"MSC","MASCABLE"));
        productBrands.add(new ProductBrand(1013559,"MTD","MTD"));
        productBrands.add(new ProductBrand(1010017,"MTG","GRUPO METALGRES"));
        productBrands.add(new ProductBrand(1010106,"MTU","CANILLAS MATEU"));
        productBrands.add(new ProductBrand(1023238,"MTX","MTX"));
        productBrands.add(new ProductBrand(1010012,"MUE","MUEBLES PARA BAÑO Y COCINA"));
        productBrands.add(new ProductBrand(1009512,"MUL","CARRETILLAS,CARRUCHAS \"MULTIPR CARRETILLAS\""));
        productBrands.add(new ProductBrand(1010033,"MU3","MULTIPRENS GRUPO 3"));
        productBrands.add(new ProductBrand(1009958,"MVL","MALLAS VALENCIA"));
        productBrands.add(new ProductBrand(1028090,"MXM","MXM"));
        productBrands.add(new ProductBrand(1009975,"MYS","MYSTRAL"));
        productBrands.add(new ProductBrand(1009513,"NAM","ACCESORIOS AUTOMORIZ           VARIOS AUTOMOTRIZ"));
        productBrands.add(new ProductBrand(1010201,"NAP","ACEITE PLOMERIRO"));
        productBrands.add(new ProductBrand(1010145,"NAR","D´COLOR"));
        productBrands.add(new ProductBrand(1009889,"NBW","PROMOCION TERRAJA PVC"));
        productBrands.add(new ProductBrand(1010081,"NEO","NEO"));
        productBrands.add(new ProductBrand(1011022,"NE1","NEO GRUPO1"));
        productBrands.add(new ProductBrand(1010922,"NE2","NE2"));
        productBrands.add(new ProductBrand(1011023,"NE3","NEO GRUPO 3"));
        productBrands.add(new ProductBrand(1011024,"NE9","NEO GRUPO 9"));
        productBrands.add(new ProductBrand(1009835,"NIM","NIPLE IMPORTADO"));
        productBrands.add(new ProductBrand(1009836,"NNA","NIPLE NACIONAL"));
        productBrands.add(new ProductBrand(1009995,"NNB","ABRAZADERAS COLGANTES"));
        productBrands.add(new ProductBrand(1013563,"NPL","NPL"));
        productBrands.add(new ProductBrand(1009888,"NR1","GLADIATOR"));
        productBrands.add(new ProductBrand(1009890,"NR2","PROMO TIJERAS IRWIN"));
        productBrands.add(new ProductBrand(1009891,"NR3","PROMO CORTAPORCELANAS IRWIN"));
        productBrands.add(new ProductBrand(1009892,"NR4","PROMO LLAVES IRWIN"));
        productBrands.add(new ProductBrand(1009893,"NR5","PROMO LLAVES ADJ IRWIN"));
        productBrands.add(new ProductBrand(1009894,"NR6","PROMO MACHOS P/ROSCAR IRWIN"));
        productBrands.add(new ProductBrand(1009897,"NR7","TIJERAS IRWIN LIQ"));
        productBrands.add(new ProductBrand(1010108,"OAT","OATEY"));
        productBrands.add(new ProductBrand(1010058,"ORI","ORION"));
        productBrands.add(new ProductBrand(1009908,"OSR","OSRAM"));
        productBrands.add(new ProductBrand(1010410,"OUT","OTSUY"));
        productBrands.add(new ProductBrand(1010411,"OVE","OVERLAND"));
        productBrands.add(new ProductBrand(1029643,"Pla","Pla"));
        productBrands.add(new ProductBrand(1009515,"PAH","MECHAS WERKA                   MECHAS."));
        productBrands.add(new ProductBrand(1009856,"PAL","PINTURAS PALCOLOR"));
        productBrands.add(new ProductBrand(1009935,"PAR","CLAVOS DE ACERO PARTEMSA"));
        productBrands.add(new ProductBrand(1010069,"PAS","PASADORES SANTA MARIA"));
        productBrands.add(new ProductBrand(1017421,"PCA","PROEXCA"));
        productBrands.add(new ProductBrand(1010107,"PCP","CANILLAS, CONEXIONES PVC"));
        productBrands.add(new ProductBrand(1028088,"PEC","PEC"));
        productBrands.add(new ProductBrand(1009882,"PEG","PEGATANKES"));
        productBrands.add(new ProductBrand(1010821,"PEN","PENTYL"));
        productBrands.add(new ProductBrand(1009976,"PER","POMOS ECONOMICOS"));
        productBrands.add(new ProductBrand(1016095,"PGR","LINTERNAS GARRITY Y LIFE GEAR"));
        productBrands.add(new ProductBrand(1015780,"PHA","PHASE"));
        productBrands.add(new ProductBrand(1009516,"PHI","PHILLIPS"));
        productBrands.add(new ProductBrand(1009827,"PHO","PHOENIX PLAST C.A."));
        productBrands.add(new ProductBrand(1010002,"PIE","PIE DE AMIGOS VARIOS"));
        productBrands.add(new ProductBrand(1015275,"PIT","PIT"));
        productBrands.add(new ProductBrand(1009968,"PLA","GENERADORES."));
        productBrands.add(new ProductBrand(1010114,"PLO","PLOMERITO"));
        productBrands.add(new ProductBrand(1012851,"PLS","PALSIL"));
        productBrands.add(new ProductBrand(1010412,"PMF","PERMAFLEX"));
        productBrands.add(new ProductBrand(1010057,"PM1","PEGA MARINA"));
        productBrands.add(new ProductBrand(1009883,"POK","PRODUCTOS OK"));
        productBrands.add(new ProductBrand(1009917,"POL","POLEAS"));
        productBrands.add(new ProductBrand(1009517,"PON","CABLES SOLDADURA Y BATERIA / B CABLES Y BORNES"));
        productBrands.add(new ProductBrand(1026409,"POT","ANASIL"));
        productBrands.add(new ProductBrand(1025891,"PP1","PUERTAS PLEGABLES 1"));
        productBrands.add(new ProductBrand(1009699,"PRA","HERRADURAS"));
        productBrands.add(new ProductBrand(1010136,"PRE","PREMIER PLUS"));
        productBrands.add(new ProductBrand(1009846,"PRM","PROMOCION ASOCIATIVA ART VARIOS"));
        productBrands.add(new ProductBrand(1009518,"PRO","ARTICULOS DE SEGURIDAD         LENTES DE SEGURIDAD, GUANTES"));
        productBrands.add(new ProductBrand(1026095,"PRT","PIERROT"));
        productBrands.add(new ProductBrand(1009823,"PSP","PROSANIPLAST"));
        productBrands.add(new ProductBrand(1012348,"PSS","PROSISAL"));
        productBrands.add(new ProductBrand(1010101,"PTT","SPRAY PINTA-T"));
        productBrands.add(new ProductBrand(1011127,"PTU","MANGUERAS DE RIEGO POLYTUBOS"));
        productBrands.add(new ProductBrand(1009822,"PUA","ALAMBRE DE PUAS"));
        productBrands.add(new ProductBrand(1022519,"PUM","PUM"));
        productBrands.add(new ProductBrand(1009906,"PUR","PURIFICADOR, FILTROS Y BUJIAS"));
        productBrands.add(new ProductBrand(1010022,"PVL","PROVOLT"));
        productBrands.add(new ProductBrand(1016604,"PVN","PVN"));
        productBrands.add(new ProductBrand(1010143,"QUI","QUIMICOLOR"));
        productBrands.add(new ProductBrand(1009519,"Q33","PEGA SOLD                      QUIMICA VICTORIA,C.A."));
        productBrands.add(new ProductBrand(1014265,"RAD","RDA"));
        productBrands.add(new ProductBrand(1027238,"RAY","RAY"));
        productBrands.add(new ProductBrand(1022299,"RCM","RCM"));
        productBrands.add(new ProductBrand(1018855,"RCT","RCT"));
        productBrands.add(new ProductBrand(1009520,"RDA","PALUSTRAS ENCAMIZAR            PALUSTRAS PARA ENCAMISAR"));
        productBrands.add(new ProductBrand(1021790,"RDG","RDG"));
        productBrands.add(new ProductBrand(1009841,"RDL","INDUSTRIAS RODANOL"));
        productBrands.add(new ProductBrand(1009702,"REG","REGULADORES DE COCINA"));
        productBrands.add(new ProductBrand(1010135,"REM","REMSPORT"));
        productBrands.add(new ProductBrand(1012750,"RES","RES"));
        productBrands.add(new ProductBrand(1009961,"RGT","REGLETAS BEST VALUE"));
        productBrands.add(new ProductBrand(1013253,"RMB","LA ANDINA"));
        productBrands.add(new ProductBrand(1009521,"RMX","RIMAX"));
        productBrands.add(new ProductBrand(1009825,"ROC","ROCA BRASIL"));
        productBrands.add(new ProductBrand(1009522,"ROD","RODAPIES PLASTICOS                  MANGUERAS CORONET"));
        productBrands.add(new ProductBrand(1009851,"ROK","ROCKWELL"));
        productBrands.add(new ProductBrand(1009523,"ROM","ROMANILLAS PARA VENTANAS       ROMANILLAS"));
        productBrands.add(new ProductBrand(1009969,"RON","BORNES RONAKA"));
        productBrands.add(new ProductBrand(1010035,"ROY","CINTAS DE REMOLQUE KING ROY"));
        productBrands.add(new ProductBrand(1010036,"RO1","INDUSTRIAS ROMAR"));
        productBrands.add(new ProductBrand(1019865,"RPS","RPS"));
        productBrands.add(new ProductBrand(1018447,"RSM","RSM"));
        productBrands.add(new ProductBrand(1009869,"RUB","RUBBERMAID"));
        productBrands.add(new ProductBrand(1010070,"RUE","RUEDAS IMSA"));
        productBrands.add(new ProductBrand(1025185,"RUL","CARRETILLAS, CARRUCHAS RUTEL"));
        productBrands.add(new ProductBrand(1009970,"RUN","RUANSA"));
        productBrands.add(new ProductBrand(1027033,"SAC","SACO"));
        productBrands.add(new ProductBrand(1009887,"SAF","DISTRIBUIDORA SANIFER G1"));
        productBrands.add(new ProductBrand(1009524,"SAL","GANCHOS PARA TECHO             AMARRES,GANCHOS L PARA TUBOS"));
        productBrands.add(new ProductBrand(1009707,"SAN","SALAS CHINAS - NACIONALES"));
        productBrands.add(new ProductBrand(1009525,"SAO","ENCERADOSD  LONA Y LONIL \"LOCO ENCERADOS.\""));
        productBrands.add(new ProductBrand(1010121,"SAT","AHORRADORES VENE SATCO"));
        productBrands.add(new ProductBrand(1009526,"SAW","LENOX"));
        productBrands.add(new ProductBrand(1009930,"SAY","GRIFERIAS SAYCO"));
        productBrands.add(new ProductBrand(1014873,"SCD","SDC"));
        productBrands.add(new ProductBrand(1009527,"SCH","GENERICAS- KONTIKI"));
        productBrands.add(new ProductBrand(1009528,"SEA","BOTA PLÁSTICA CAÑA ALTA SEABO"));
        productBrands.add(new ProductBrand(1009861,"SEB","BOTAS DE SEGURIDAD"));
        productBrands.add(new ProductBrand(1009529,"SEG","SEGURIDAD INDUSTRIAL"));
        productBrands.add(new ProductBrand(1009530,"SEL","SELLADOR PARA  JUNTAS DE CERAM SELLADORES"));
        productBrands.add(new ProductBrand(1022930,"SEM","SEM"));
        productBrands.add(new ProductBrand(1009531,"SEV","SEÑALIZACIONES SEVEN           SEÑALIZACIONES DE SEGURIDAD INDUSTRIAL"));
        productBrands.add(new ProductBrand(1010037,"SE1","BOTAS SEGURIDAD SEABOOTS"));
        productBrands.add(new ProductBrand(1010719,"SE3","ACCESORIOS PARA SOLDADOR"));
        productBrands.add(new ProductBrand(1019256,"SFB","SAFARI BOOTS"));
        productBrands.add(new ProductBrand(1013659,"SGA","BOTA DE SEGURIDAD SAGA"));
        productBrands.add(new ProductBrand(1023745,"SGU","SGU"));
        productBrands.add(new ProductBrand(1027442,"SG1","SG1"));
        productBrands.add(new ProductBrand(1009813,"SHI","BRISWAY CERRADURAS"));
        productBrands.add(new ProductBrand(1011937,"SIC","SIC"));
        productBrands.add(new ProductBrand(1009952,"SID","SIDERO GALVANICA, C.A."));
        productBrands.add(new ProductBrand(1009837,"SIE","BREAKER SIEMENS"));
        productBrands.add(new ProductBrand(1009938,"SIK","SIKA"));
        productBrands.add(new ProductBrand(1009532,"SIM","CERRADURAS DE SEGURIDAD STAR   CERRADURAS DE SEGURIDAD"));
        productBrands.add(new ProductBrand(1009533,"SIS","MECATE SISAL"));
        productBrands.add(new ProductBrand(1010092,"SI1","CONTACTORES Y RELES SIEMENS"));
        productBrands.add(new ProductBrand(1009928,"SI2","LINEA ILUS SIEMENS"));
        productBrands.add(new ProductBrand(1010096,"SI3","LINEA TALARI SIEMENS"));
        productBrands.add(new ProductBrand(1010120,"SI4","LINEA DUAL SIEMENS"));
        productBrands.add(new ProductBrand(1010099,"SK2","SIKA G2"));
        productBrands.add(new ProductBrand(1009896,"SLI","SLINGAS AMAZONICAS"));
        productBrands.add(new ProductBrand(1009534,"SLT","SOPORTES PARA BOTELLONES       SALTOS DE ANGEL (SOPORTES P/AGUA POTABLE)"));
        productBrands.add(new ProductBrand(1009923,"SMN","SIEMENS TOMAS INTERRUPTORES"));
        productBrands.add(new ProductBrand(1010034,"SNS","CINTAS GANCHO PLANO Y RACHET SANSON"));
        productBrands.add(new ProductBrand(1010083,"SOE","LINTERNA Y LAMPARA SOLAR"));
        productBrands.add(new ProductBrand(1009709,"SOL","SOLPOWER"));
        productBrands.add(new ProductBrand(1009957,"SOS","ART EN SOS"));
        productBrands.add(new ProductBrand(1009535,"SOV","SOVICA"));
        productBrands.add(new ProductBrand(1009985,"SOZ","SOLUZION"));
        productBrands.add(new ProductBrand(1010055,"SPC","CAJAS ORGANIZADORAS SPLACA"));
        productBrands.add(new ProductBrand(1009536,"SPE","SPEDRITE                       COMPONENTE CERCO ELECTRICO"));
        productBrands.add(new ProductBrand(1010125,"SPI","SPIDERFLEX"));
        productBrands.add(new ProductBrand(1009537,"SPL","BOYAS, DESAGUES, SIFONES, EXT, ARTICULOS DE PLOMERIA"));
        productBrands.add(new ProductBrand(1022197,"SPM","SPECTRUM"));
        productBrands.add(new ProductBrand(1009838,"SPR","SPRAY PINTURA."));
        productBrands.add(new ProductBrand(1009859,"SPT","CABLES SPT"));
        productBrands.add(new ProductBrand(1010021,"SQ3","SPRAY QUIMICA AUTOMOTRIZ"));
        productBrands.add(new ProductBrand(1013053,"STL","STL"));
        productBrands.add(new ProductBrand(1019155,"STV","STV"));
        productBrands.add(new ProductBrand(1012144,"SUA","INVERSIONES SUAREZ ESC, C.A."));
        productBrands.add(new ProductBrand(1009712,"SUF","SUFEIN"));
        productBrands.add(new ProductBrand(1026200,"SUM","SUM"));
        productBrands.add(new ProductBrand(1024666,"SUN","SUN"));
        productBrands.add(new ProductBrand(1009862,"SUR","CABOS-CONSTRUSUR XXI"));
        productBrands.add(new ProductBrand(1009538,"SW1","COLONIAL VP"));
        productBrands.add(new ProductBrand(1009948,"SW2","DOMINO CAUCHO VP"));
        productBrands.add(new ProductBrand(1010098,"SW3","DOMINO ESMALTE VP"));
        productBrands.add(new ProductBrand(1010100,"SW4","KEM - AMBIENT VP"));
        productBrands.add(new ProductBrand(1009885,"SW5","FONDOS VP"));
        productBrands.add(new ProductBrand(1028077,"SW6","COMPLEMENTARIOS VP"));
        productBrands.add(new ProductBrand(1009996,"TB1","TUBRICA AGUAS NEGRAS"));
        productBrands.add(new ProductBrand(1009997,"TB2","TUBRICA AGUA FRIA"));
        productBrands.add(new ProductBrand(1009998,"TB3","TUBRICA AGUA CALIENTE"));
        productBrands.add(new ProductBrand(1009999,"TB4","TUBRICA ELECTRICOS CONDUIT"));
        productBrands.add(new ProductBrand(1018653,"TB5","TB5"));
        productBrands.add(new ProductBrand(1009713,"TEK","MARCA TEK"));
        productBrands.add(new ProductBrand(1009909,"TER","ENCERADOS TERYLENE"));
        productBrands.add(new ProductBrand(1018754,"TEZ","TEZ"));
        productBrands.add(new ProductBrand(1009956,"THH","CABLES THHN"));
        productBrands.add(new ProductBrand(1016605,"THW","CABLES THHW"));
        productBrands.add(new ProductBrand(1010105,"TIG","PVC ROSCADO TIGRE"));
        productBrands.add(new ProductBrand(1010091,"TIR","TIRADORES"));
        productBrands.add(new ProductBrand(1014063,"TLC","TOOLCRAFT"));
        productBrands.add(new ProductBrand(1016908,"TNU","TNU"));
        productBrands.add(new ProductBrand(1010122,"TOD","TODO CONSTRUCTOR"));
        productBrands.add(new ProductBrand(1009920,"TOP","BOTAS GOMA TOP RAIN"));
        productBrands.add(new ProductBrand(1009539,"TOR","TORNILLOS"));
        productBrands.add(new ProductBrand(1010102,"TPE","TEIPE"));
        productBrands.add(new ProductBrand(1009863,"TRA","TRAMONTINA"));
        productBrands.add(new ProductBrand(1009864,"TRB","SALAS DE BAÑO TREBOL"));
        productBrands.add(new ProductBrand(1027139,"TRC","TRC"));
        productBrands.add(new ProductBrand(1009540,"TRD","BISAGRAS Y TIRADORES"));
        productBrands.add(new ProductBrand(1009867,"TRE","TREXA"));
        productBrands.add(new ProductBrand(1023951,"TRF","TRF"));
        productBrands.add(new ProductBrand(1009947,"TRI","MALLAS TRICAL"));
        productBrands.add(new ProductBrand(1017110,"TRL","TRL"));
        productBrands.add(new ProductBrand(1028192,"TRN","TRN"));
        productBrands.add(new ProductBrand(1009949,"TRO","LANA DE ACERO TROYA"));
        productBrands.add(new ProductBrand(1029120,"TRP","TRP"));
        productBrands.add(new ProductBrand(1010007,"TRY","REMACHES TROYA"));
        productBrands.add(new ProductBrand(1009881,"TSC","TUBERIA SCHEDULE"));
        productBrands.add(new ProductBrand(1015789,"TST","TUCSON TOOL"));
        productBrands.add(new ProductBrand(1009716,"TS1","TUBERIA SCHD80/ LIVIANA DERIVA"));
        productBrands.add(new ProductBrand(1010514,"TTU","CABLES ESPECIALES"));
        productBrands.add(new ProductBrand(1009541,"TUB","TUBRICA"));
        productBrands.add(new ProductBrand(1010000,"TUI","TUBERIA SCHEDULE INPLAVEN"));
        productBrands.add(new ProductBrand(1009542,"TUM","TUBERIA DE AGUAS NEGRAS VARIAS TUBOS DE AGUAS NEGRAS"));
        productBrands.add(new ProductBrand(1010016,"TUP","MANGUERAS DE RIEGO"));
        productBrands.add(new ProductBrand(1009543,"UM9","CONEXIONES DE AGUAS NEGRAS VAR CONEXIONES UM"));
        productBrands.add(new ProductBrand(1009717,"UNI","UNICON"));
        productBrands.add(new ProductBrand(1010011,"URI","URINARIOS Y OTRAS PIEZAS INSTITUCIONALES"));
        productBrands.add(new ProductBrand(1010131,"URS","PIE AMIGO FIJO"));
        productBrands.add(new ProductBrand(1010013,"UR1","URINARIO"));
        productBrands.add(new ProductBrand(1015076,"USA","USA"));
        productBrands.add(new ProductBrand(1009945,"VAL","Productos Valcro"));
        productBrands.add(new ProductBrand(1009718,"VAR","VARILLAS DE HIERRO"));
        productBrands.add(new ProductBrand(1018031,"VCR","VALCRO"));
        productBrands.add(new ProductBrand(1014064,"VCS","VIDRIO CARETA SOLDAR"));
        productBrands.add(new ProductBrand(1012853,"VDS","VENEZOLANA DE SPRAY"));
        productBrands.add(new ProductBrand(1015476,"VDV","VDVD"));
        productBrands.add(new ProductBrand(1009829,"VEN","LAMINAS DE ZINC"));
        productBrands.add(new ProductBrand(1009852,"VER","TIMBRES Y CANDADOS VERA"));
        productBrands.add(new ProductBrand(1010067,"VE1","VENPLUS"));
        productBrands.add(new ProductBrand(1027030,"VIK","VIK"));
        productBrands.add(new ProductBrand(1009866,"VIS","VISEGRIP"));
        productBrands.add(new ProductBrand(1021583,"VIT","VIT"));
        productBrands.add(new ProductBrand(1023748,"VIV","VIV"));
        productBrands.add(new ProductBrand(1024768,"VLF","VLF"));
        productBrands.add(new ProductBrand(1010119,"VL2","VENSOLINA"));
        productBrands.add(new ProductBrand(1026405,"VNC","VNC"));
        productBrands.add(new ProductBrand(1028060,"VNM","VENICOM"));
        productBrands.add(new ProductBrand(1010029,"VNS","VENUS LLANERA"));
        productBrands.add(new ProductBrand(1026926,"VOL","ECOCOLT"));
        productBrands.add(new ProductBrand(1022305,"VRS","VENEZUELA RIVETS"));
        productBrands.add(new ProductBrand(1010005,"VSL","VENSOL"));
        productBrands.add(new ProductBrand(1010137,"VS3","VENEZOLANA DE SPRAY."));
        productBrands.add(new ProductBrand(1028306,"VTS","VICTUSA"));
        productBrands.add(new ProductBrand(1010134,"VY1","MANGUERAS VEYANCE G1"));
        productBrands.add(new ProductBrand(1010072,"V90","FLUXOMETROS SLOAN"));
        productBrands.add(new ProductBrand(1010064,"V91","VENCERAMICA ART SUELTOS"));
        productBrands.add(new ProductBrand(1009914,"V92","VENCERAMICA X ELIMINAR"));
        productBrands.add(new ProductBrand(1009913,"V93","LLAVE ARRESTO + CANILLA"));
        productBrands.add(new ProductBrand(1009848,"V94","VENCERAMICA SALAS BLANCAS OPP"));
        productBrands.add(new ProductBrand(1009544,"V95","VENCERAMICA (Griferias; Valvulas y Repuestos)"));
        productBrands.add(new ProductBrand(1009545,"V96","VENCERAMICA WC-LAVAMANOS-URINARIOS NO OPP"));
        productBrands.add(new ProductBrand(1009812,"V97","VENCERAMICA Salas Colores"));
        productBrands.add(new ProductBrand(1009844,"V98","VENCERAMICA ASIENTOS"));
        productBrands.add(new ProductBrand(1009845,"V99","VENCERAMICA HERRAJES"));
        productBrands.add(new ProductBrand(1009981,"WAL","BROCHAS WALLDONE"));
        productBrands.add(new ProductBrand(1010615,"WCO","WALCO."));
        productBrands.add(new ProductBrand(1026821,"WDH","WDH"));
        productBrands.add(new ProductBrand(1013658,"WIN","WINNER"));
        productBrands.add(new ProductBrand(1010141,"WLC","WALCO"));
        productBrands.add(new ProductBrand(1011941,"WLV","WLV"));
        productBrands.add(new ProductBrand(1028613,"WOO","WOO"));
        productBrands.add(new ProductBrand(1013958,"WOR","WOREY"));
        productBrands.add(new ProductBrand(1025285,"WOS","WOS"));
        productBrands.add(new ProductBrand(1010071,"WQP","CERRADURAS WEQUP"));
        productBrands.add(new ProductBrand(1010140,"WT","WELDTECH"));
        productBrands.add(new ProductBrand(1011126,"WVE","WAL"));
        productBrands.add(new ProductBrand(1017622,"WYE","WYE"));
        productBrands.add(new ProductBrand(1015677,"XAN","XAN"));
        productBrands.add(new ProductBrand(1010082,"XIA","VIDRIO PARA CARETA"));
        productBrands.add(new ProductBrand(1028308,"XIL","XIL"));
        productBrands.add(new ProductBrand(1015783,"XIO","XIO"));
        productBrands.add(new ProductBrand(1023848,"XXX","XXX"));
        productBrands.add(new ProductBrand(1009546,"YAI","BREAKER GENERICO               MATERIALES CHANYU -  IMPORTADORA GREVI"));
        productBrands.add(new ProductBrand(1009547,"YAL","CANDADOS Y CERRADURAS YALE     CERRADURAS, CANDADOS"));
        productBrands.add(new ProductBrand(1024972,"YAN","YAN"));
        productBrands.add(new ProductBrand(1029646,"ZEG","ZEGA"));
        productBrands.add(new ProductBrand(1027034,"ZET","ZETA IMPORT"));
        productBrands.add(new ProductBrand(1028079,"ZOE","ZOE"));
        productBrands.add(new ProductBrand(1019966,"ZOG","ZOG"));
        productBrands.add(new ProductBrand(1009395,"0C2","ABRAZ. Y TAPAS GALVANIZAD IND. FERREINOX"));
        productBrands.add(new ProductBrand(1022310,"001","COMBOS"));
        productBrands.add(new ProductBrand(1009596,"003","PLASTICO DE EMPAQUE"));
        productBrands.add(new ProductBrand(1009597,"004","MECATES LOS ELEFANTES - CORDELERIA OCCIDENTAL"));
        productBrands.add(new ProductBrand(1009598,"005","MECATES SISALARA"));
        productBrands.add(new ProductBrand(1009599,"006","CORDELES Y GUARALES"));
        productBrands.add(new ProductBrand(1020882,"02A","02A"));
        productBrands.add(new ProductBrand(1010023,"02B","DIAMANTADOS NORTON"));
        productBrands.add(new ProductBrand(1010104,"09T","TIJERAS 12P BELLOTA"));
        productBrands.add(new ProductBrand(1009414,"102","FESTA                          DIST. LINIAS, DILISA SERDEL ; FESTA"));
        productBrands.add(new ProductBrand(1009415,"105","SEÑORITAS MANUALES - WINCHES   HERRAMIENTAS DE MANO, GRIFERIA, MAT ELECTRICOS"));
        productBrands.add(new ProductBrand(1009726,"106","MARCA 106"));
        productBrands.add(new ProductBrand(1009416,"109","TRAPOS Y ESTOPAS               P"));
        productBrands.add(new ProductBrand(1009729,"111","IMPERMEABLES Y PONCHOS"));
        productBrands.add(new ProductBrand(1009417,"115","BIDONES Y CARRETES"));
        productBrands.add(new ProductBrand(1009733,"116","Angulos"));
        productBrands.add(new ProductBrand(1009734,"117","Flanches"));
        productBrands.add(new ProductBrand(1009735,"118","Tubo estructural"));
        productBrands.add(new ProductBrand(1009736,"119","Tubos de ventilacion"));
        productBrands.add(new ProductBrand(1009738,"120","Tubo rectangular, cuadrado"));
        productBrands.add(new ProductBrand(1009739,"121","Pletinas"));
        productBrands.add(new ProductBrand(1009742,"126","MARCA 126"));
        productBrands.add(new ProductBrand(1009418,"135","EMBUDOS                        EMBUDO, CONEXION"));
        productBrands.add(new ProductBrand(1010126,"15%","DESCUENTO POR CIERRE DE INVENTARIO"));
        productBrands.add(new ProductBrand(1009419,"151","ACCESORIOS PINTAR              EQUIPOS DE PINTURA."));
        productBrands.add(new ProductBrand(1009420,"167","PRODUCTOS ASFALTICOS BLACK CAR GALON DE BLACK CAR TRES"));
        productBrands.add(new ProductBrand(1009421,"170","PORTACANDADOS, PASADORES, ROLD IND. RODAMA - IND FAXA - IND ROMAR - MET VIERANTE"));
        productBrands.add(new ProductBrand(1009422,"182","COMEC - VOTTO                  VARIOS."));
        productBrands.add(new ProductBrand(1009784,"183","MARCA 183"));
        productBrands.add(new ProductBrand(1009423,"189","ANZUELOS                       ANZUELO, NYLON"));
        productBrands.add(new ProductBrand(1009424,"195","COOPER"));
        productBrands.add(new ProductBrand(1009794,"196","COOPER TOMAS 270"));
        productBrands.add(new ProductBrand(1009425,"198","OXIDOS DE HIERRO PARA PISO     OXIDOS"));
        productBrands.add(new ProductBrand(1009426,"199","POLEAS, GARRUCHAS              RUEDAS P/PORTON, GARRUCHAS"));
        productBrands.add(new ProductBrand(1009427,"200","FLOTANTES Y SURTIDOR DE BRONCE FLOTANTE VENE-MASTER"));
        productBrands.add(new ProductBrand(1009428,"201","UÑAS P/LAVAMANO, TAPAHUECO FRE PRODUCTOS TUB."));
        productBrands.add(new ProductBrand(1009429,"205","FILTROS BERKEFEL               GRIFERIAS"));
        productBrands.add(new ProductBrand(1009430,"208","AYA FONDOS ANTICORROSIVOS A    ANTICORROSIVOS Y ACABADOS AYA C.A."));
        productBrands.add(new ProductBrand(1009431,"214","STANLEY"));
        productBrands.add(new ProductBrand(1009432,"223","PHILIPS ( BOMBILLOS Y BALASTO) BOMBILLOS, TUBOS FLUORESCENTES."));
        productBrands.add(new ProductBrand(1009934,"3M","3M MANUFACTURERA VENEZUELA"));
        productBrands.add(new ProductBrand(1010001,"3M1","3M AUTOMOTRIZ"));
        productBrands.add(new ProductBrand(1027647,"305","305"));
        productBrands.add(new ProductBrand(1009433,"332","AEROCLOSET                     PRODUCTOS AEROCLOSET"));
        productBrands.add(new ProductBrand(1017009,"366","366"));
        productBrands.add(new ProductBrand(1029952,"4EV","4EV"));
        productBrands.add(new ProductBrand(1009922,"420","BES"));
        productBrands.add(new ProductBrand(1009366,"55P","PROLIFE, C.A"));
        productBrands.add(new ProductBrand(1027948,"6TA","6TA"));
        productBrands.add(new ProductBrand(1009916,"69A","CONEXIONES GALVANIZADAS"));
        productBrands.add(new ProductBrand(1009879,"781","TUBERIA DE CERCA"));
        productBrands.add(new ProductBrand(1010014,"83A","SAPOLINES"));
        productBrands.add(new ProductBrand(1009434,"888","CANDADOS Y CERRADURAS SECURITY CANDADOS DE LATON Y ANTICIZALLA CHINOS"));
        productBrands.add(new ProductBrand(1009870,"901","CLAVOS A GRANEL"));
        productBrands.add(new ProductBrand(1009877,"902","CLAVOS EMPACADOS VICSON"));
        productBrands.add(new ProductBrand(1009871,"903","MALLAS PAJARERAS"));
        productBrands.add(new ProductBrand(1009872,"904","MALLAS POLLITO"));
        productBrands.add(new ProductBrand(1009873,"905","MALLAS VICSON (TODAS)"));
        productBrands.add(new ProductBrand(1009875,"906","GRAPAS VICSON"));
        productBrands.add(new ProductBrand(1009876,"907","ALAMBRES DE PUAS VICSON"));
        productBrands.add(new ProductBrand(1009874,"908","ALAMBRES LISOS GALV"));
        productBrands.add(new ProductBrand(1009942,"909","ALAMBRE IMPORTADO"));
        productBrands.add(new ProductBrand(1010138,"910","DRAMIX"));
    }

}
