package com.smartbuilders.smartsales.ecommerceandroidapp.utils;

import java.util.ArrayList;

/**
 * Created by Alberto on 25/4/2016.
 */
public class UtilsMainPageProduct {

    private ArrayList<String> insert;

    public ArrayList<String> getInserts(){
        return insert;
    }

    public UtilsMainPageProduct(){
        insert = new ArrayList<>();

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (1, 1, 1096674, 1, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (2, 1, 1096671, 2, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (3, 1, 1093781, 3, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (4, 1, 1095891, 4, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (5, 1, 1096671, 5, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (6, 2, 1184941, 6, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (7, 2, 1083810, 7, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (8, 2, 1188388, 8, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (9, 2, 1197943, 9, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (10, 2, 1087177, 10, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (11, 3, 1093776, 11, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (12, 3, 1089831, 12, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (13, 3, 1124155, 13, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (14, 3, 1087174, 14, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (15, 3, 1089314, 15, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (16, 4, 1081133, 1, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (17, 4, 1110834, 2, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (18, 4, 1087719, 3, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (19, 4, 1089449, 4, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (20, 4, 1087176, 5, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (21, 5, 1083799, 6, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (22, 5, 1083810, 7, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (23, 5, 1170110, 8, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (24, 5, 1170109, 9, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (25, 5, 1184942, 10, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (26, 6, 1093854, 11, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (27, 6, 1106416, 12, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (28, 6, 1085113, 13, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (29, 6, 1093506, 14, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (30, 6, 1209396, 15, 'Y')");
    }
}
