package com.smartbuilders.smartsales.ecommerceandroidapp.utils;

import java.util.ArrayList;

/**
 * Created by Alberto on 25/4/2016.
 */
public class UtilsMainPageProduct {

    private ArrayList<String> insert;

    public ArrayList<String> getInserts(){
        return insert;
    }

    public UtilsMainPageProduct(){
        insert = new ArrayList<>();

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (1, 1, 1078895, 1, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (2, 1, 1079014, 2, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (3, 1, 1079358, 3, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (4, 1, 1079436, 4, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (5, 1, 1079482, 5, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (6, 1, 1079561, 6, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (7, 1, 1096671, 7, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (8, 1, 1079573, 8, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (9, 1, 1079672, 9, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (10, 1, 1079800, 10, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (11, 1, 1096674, 11, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (12, 1, 1096671, 12, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (13, 1, 1093781, 13, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (14, 1, 1095891, 14, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (15, 1, 1096671, 15, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (16, 2, 1184941, 1, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (17, 2, 1083810, 2, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (18, 2, 1188388, 3, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (19, 2, 1197943, 4, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (20, 2, 1087177, 5, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (21, 2, 1184941, 6, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (22, 2, 1083810, 7, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (23, 2, 1188388, 8, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (24, 2, 1197943, 9, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (25, 2, 1087177, 10, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (26, 2, 1184941, 11, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (27, 2, 1083810, 12, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (28, 2, 1188388, 13, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (29, 2, 1197943, 15, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (30, 2, 1087177, 16, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (31, 3, 1093776, 11, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (32, 3, 1089831, 12, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (33, 3, 1124155, 13, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (34, 3, 1087174, 14, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (35, 3, 1089314, 15, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (36, 3, 1093776, 16, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (37, 3, 1089831, 17, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (38, 3, 1124155, 18, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (39, 3, 1087174, 19, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (40, 3, 1089314, 20, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (41, 3, 1093776, 21, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (42, 3, 1089831, 22, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (43, 3, 1124155, 23, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (44, 3, 1087174, 24, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (45, 3, 1089314, 25, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (46, 4, 1081133, 1, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (47, 4, 1110834, 2, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (48, 4, 1087719, 3, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (49, 4, 1089449, 4, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (50, 4, 1087176, 5, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (51, 4, 1081133, 6, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (52, 4, 1110834, 7, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (53, 4, 1087719, 8, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (54, 4, 1089449, 9, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (55, 4, 1087176, 10, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (56, 4, 1081133, 11, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (57, 4, 1110834, 12, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (58, 4, 1087719, 13, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (59, 4, 1089449, 14, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (60, 4, 1087176, 15, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (61, 5, 1083799, 1, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (62, 5, 1083810, 2, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (63, 5, 1170110, 3, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (64, 5, 1170109, 4, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (65, 5, 1184942, 5, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (66, 5, 1083799, 6, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (67, 5, 1083810, 7, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (68, 5, 1170110, 8, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (69, 5, 1170109, 9, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (70, 5, 1184942, 10, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (71, 5, 1083799, 11, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (72, 5, 1083810, 12, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (73, 5, 1170110, 13, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (74, 5, 1170109, 14, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (75, 5, 1184942, 15, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (76, 6, 1093854, 11, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (77, 6, 1106416, 12, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (78, 6, 1085113, 13, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (79, 6, 1093506, 14, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (80, 6, 1209396, 15, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (81, 6, 1093854, 16, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (82, 6, 1106416, 17, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (83, 6, 1085113, 18, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (84, 6, 1093506, 19, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (85, 6, 1209396, 20, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (86, 6, 1093854, 21, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (87, 6, 1106416, 22, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (88, 6, 1085113, 23, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (89, 6, 1093506, 24, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (90, 6, 1209396, 25, 'Y')");
    }
}
