package com.smartbuilders.smartsales.ecommerceandroidapp.utils;

import java.util.ArrayList;

/**
 * Created by Alberto on 25/4/2016.
 */
public class UtilsMainPageProduct {

    private ArrayList<String> insert;

    public ArrayList<String> getInserts(){
        return insert;
    }

    public UtilsMainPageProduct(){
        insert = new ArrayList<>();
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (1, 1, 1078878, 1, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (2, 1, 1078879, 2, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (3, 1, 1078882, 3, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (4, 1, 1078883, 4, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (5, 1, 1078889, 5, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (6, 2, 1078891, 6, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (7, 2, 1078893, 7, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (8, 2, 1078894, 8, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (9, 2, 1078895, 9, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (10, 2, 1078896, 10, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (11, 3, 1078902, 11, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (12, 3, 1078905, 12, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (13, 3, 1078907, 13, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (14, 3, 1078908, 14, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (15, 3, 1078910, 15, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (16, 4, 1090821, 1, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (17, 4, 1090827, 2, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (18, 4, 1090833, 3, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (19, 4, 1090839, 4, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (20, 4, 1090853, 5, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (21, 5, 1083247, 6, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (22, 5, 1083248, 7, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (23, 5, 1083249, 8, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (24, 5, 1083251, 9, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (25, 5, 1083259, 10, 'Y')");

        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (26, 6, 1096884, 11, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (27, 6, 1096893, 12, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (28, 6, 1096911, 13, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (29, 6, 1096947, 14, 'Y')");
        insert.add("insert into MAINPAGE_PRODUCT (MAINPAGE_PRODUCT_ID, MAINPAGE_SECTION_ID, PRODUCT_ID, PRIORITY, ISACTIVE) values (30, 6, 1097229, 15, 'Y')");
    }
}
