package com.smartbuilders.smartsales.ecommerceandroidapp.utils;

import java.util.ArrayList;

/**
 * Created by stein on 4/23/2016.
 */
public class UtilsSubCategory {

    private ArrayList<String> insert;

    public ArrayList<String> getInserts(){
        return insert;
    }

    public UtilsSubCategory(){
        insert = new ArrayList<>();
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002873, 1000239, '1', 'COMBOS GRUPO 0', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002874, 1000239, '2', 'ACEITERAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002875, 1000239, '10', 'ALICATES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002876, 1000239, '12', 'JGO. DE HERRAMIENTAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002877, 1000239, '20', 'PROBADORES DE VOLTAJE / MULTITESTER', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002878, 1000239, '30', 'AUTOCLETS - RATCHETS - EXTENSIONES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002879, 1000239, '50', 'BROCHAS - ACCESORIOS DE PINTURA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002880, 1000239, '130', 'CINCELES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002881, 1000239, '141', 'CINTA PASACABLE', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002882, 1000239, '150', 'CIZALLAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002883, 1000239, '180', 'CORTAPORCELANA - CORTATUBO - CORTAVIDRIO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002884, 1000239, '190', 'CUCHARAS DE ALBAÑIL', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002885, 1000239, '200', 'CUCHILLAS - NAVAJAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002886, 1000239, '208', 'DADOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002887, 1000239, '220', 'CHUPONES DE GOMA PARA CAÑERIA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002888, 1000239, '230', 'DESTORNILLADORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002889, 1000239, '260', 'ENGRASADORAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002890, 1000239, '280', 'MEDICION', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002891, 1000239, '290', 'ESMERILES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002892, 1000239, '300', 'ESPATULAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002893, 1000239, '320', 'KIT P/LATONERO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002894, 1000239, '340', 'FORMONES - GUBIAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002895, 1000239, '365', 'LIJADORAS - TROMPOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002896, 1000239, '370', 'LIMAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002897, 1000239, '380', 'LLAVES COMB.- AJUST.- TUBO - ALLEN - CRUZ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002898, 1000239, '410', 'MARTILLOS - MACETAS - MAZOS - MANDARRIAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002899, 1000239, '420', 'MECHAS - MACHOS PARA ROSCA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002900, 1000239, '430', 'NIVELES Y CALIBRADORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002901, 1000239, '440', 'PALUSTRAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002902, 1000239, '450', 'PIQUETAS ALBAÑIL', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002903, 1000239, '460', 'COMPRESORES - PISTOLAS - ACCESORIOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002904, 1000239, '470', 'PLOMADA PARA ALBAÑIL', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002905, 1000239, '480', 'PORTA-ELECTRODOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002906, 1000239, '485', 'PINZA TIERRA SOLDAR', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002907, 1000239, '490', 'PRENSAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002908, 1000239, '510', 'REMACHES - REMACHADORAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002909, 1000239, '540', 'RIBETEADOR', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002910, 1000239, '550', 'SALPICADORAS Y REPUESTOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002911, 1000239, '560', 'SEGUETAS - SIERRA COPA - HOJAS P/ CALADORA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002912, 1000239, '561', 'ARCOS P/SEGUETA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002913, 1000239, '570', 'SERRUCHOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002914, 1000239, '580', 'TRONZADORAS - INGLETEADORAS - SIERRAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002915, 1000239, '590', 'MAQ.SOLDAR - EQUIP.OXICORTE - CAUTIN - ESTAÑO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002916, 1000239, '600', 'SOPLETES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002917, 1000239, '610', 'TALADROS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002918, 1000239, '611', 'MANDRIL - LLAVE MANDRIL - KIT CERRAD.- JGOS.VARIOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002919, 1000239, '620', 'TENAZAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002920, 1000239, '630', 'TERRAJAS - DADOS PARA TERRAJA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002921, 1000239, '640', 'TIJERAS HOJALATERA - AVIACION', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002922, 1000239, '650', 'TIRALINEAS - TIZAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002923, 1000239, '998', 'EXHIBIDORES,MATERIAL POP, GENERAL MERCHANDISING.', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002924, 1000239, '105', 'MAQUINARIA PESADA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002925, 1000239, '140', 'CINTA METRICA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002926, 1000240, '1', 'COMBOS GRUPO 1', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002927, 1000240, '10', 'BARRAS PARA HOYAR', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002928, 1000240, '20', 'BOMBAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002929, 1000240, '30', 'DESMALEZADORA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002930, 1000240, '40', 'CABOS DE MADERA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002931, 1000240, '120', 'CAVADORAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002932, 1000240, '140', 'CHICURAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002933, 1000240, '160', 'ESCARDILLA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002934, 1000240, '200', 'KIT JARDINERIA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002935, 1000240, '220', 'FUMIGADORAS,ROCIADORES SPRAY', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002936, 1000240, '260', 'HACHAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002937, 1000240, '270', 'CUCHILLA GUADAÑADORA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002938, 1000240, '300', 'MACHETES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002939, 1000240, '340', 'PALAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002940, 1000240, '360', 'PALINES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002941, 1000240, '400', 'PICOS (PUNTA Y PALA - GAMELOTEROS)', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002942, 1000240, '440', 'ACCESORIOS PARA CERCAS TIPO CICLON', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002943, 1000240, '290', 'CUCHILLOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002945, 1000240, '130', 'ESCOBAS DE JARDIN Y RASTRILLOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002946, 1000240, '141', 'CONEXIONES Y ACCESORIOS DE RIEGO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002947, 1000240, '190', 'TIJERAS PARA JARDIN', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002948, 1000240, '150', 'MANGUERAS DE RIEGO Y JARDIN', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002949, 1000240, '21', 'HIDRONEUMATICOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002950, 1000240, '22', 'MOTOBOMBAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002951, 1000240, '31', 'CORTAGRAMA Y SOPLADORA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002952, 1000240, '32', 'MOTOSIERRA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002953, 1000240, '33', 'ACC. PARA DESM/CORTG/MOTOSIERRA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002954, 1000240, '142', 'ACC DE RIEGO PARA JARDIN', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002955, 1000240, '19', 'HIDROLAVADORAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002956, 1000240, '24', 'GENERADORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002957, 1000240, '998', 'EXHIBIDORES G1', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002958, 1000241, '1', 'COMBOS GRUPO 2', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002959, 1000241, '4', 'BOTELLON Y ACC DE SURTIDOR DE AGUA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002960, 1000241, '8', 'CADENAS P/PERROS Y MATEROS, PECHERAS Y COLLARES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002961, 1000241, '11', 'COCINAS Y REGULADORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002962, 1000241, '12', 'MOLINO PARA MAIZ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002963, 1000241, '40', 'ESCALERAS D/ALUMINIO TIJERA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002964, 1000241, '92', 'TRAMPAS Y COLA PARA RATAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002965, 1000241, '129', 'CEPILLOS P/BARRER', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002966, 1000241, '140', 'MANGUERAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002967, 1000241, '205', 'ANZUELOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002968, 1000241, '208', 'BALINES PARA FLOWERS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002969, 1000241, '233', 'PLOMO EN LAMINA Y DE PESCA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002970, 1000241, '235', 'NYLON DE PESCA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002971, 1000241, '236', 'CARRETE PLASTICO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002972, 1000241, '320', 'LIJA, ROLLOS, FIBRODISCOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002973, 1000241, '324', 'LANA DE ACERO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002974, 1000241, '330', 'TIRROS Y CINTAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002975, 1000241, '352', 'ACEITE P/ROSCA, SILICONAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002976, 1000241, '365', 'PEGA METYLAN Y COLA BLANCA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002977, 1000241, '370', 'MASTIQUE Y PASTA PROF.', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002978, 1000241, '375', 'PEGAS P/TUBERIAS PVC', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002979, 1000241, '380', 'CEMENTOS DE CONTACTO Y CREOLINA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002980, 1000241, '385', 'PEGAS EPOXICAS E INSTANTANEAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002981, 1000241, '390', 'PINT. SAPOLIN, SPRAY, FONDOS Y MASILLAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002982, 1000241, '391', 'PINTURAS Y ACABADOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002983, 1000241, '395', 'TEFLONES, CINTAS ELECTRICAS Y DOBLE FAZ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002984, 1000241, '960', 'PESOS, BALANZAS Y BASCULAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002985, 1000241, '990', 'TERMOS Y GRIFOS P/TERMOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002986, 1000241, '998', 'EXHIBIDORES Y POP', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002987, 1000241, '321', 'DISCOS DE CORTE Y DESBASTE', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002988, 1000241, '322', 'CEPILLOS DE COPA, CIRCULARES Y DE USO MANUAL', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002989, 1000241, '120', 'LIMPIADOR DE GRIFERIA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002990, 1000242, '1', 'COMBOS GRUPO 3', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002991, 1000242, '10', 'GUARAL SINTETICO Y CABUYA BALER TWINE', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002992, 1000242, '11', 'CABUYA SISAL', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002993, 1000242, '20', 'LAMPARA AUXILIARES, BORNES DE BATERIAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002994, 1000242, '30', 'DRIZAS DE NYLON', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002995, 1000242, '40', 'ENCERADOS LONA VERDE(BAJA TENACIDAD)', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002996, 1000242, '41', 'ENCERADOS PLASTICOS(ALTA TENACIDAD)', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002997, 1000242, '45', 'PLASTICO(TRANSPARENTE Y NEGRO)', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002998, 1000242, '60', 'ESTOPAS,TRAPOS Y ALGODON', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1002999, 1000242, '80', 'IMPERMEABLES,CORDONES ELAST.', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003000, 1000242, '100', 'MECATE (TODO TIPO)', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003001, 1000242, '150', 'CARBONES PARA EQUIPOS Y HERRAMIENTAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003002, 1000242, '43', 'CINTAS  RATCHET Y GANCHO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003003, 1000242, '420', 'SEÑORITAS Y WINCHES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003004, 1000242, '350', 'GATOS DE BOTELLA, GATOS CAIMAN, GATO PARA RUSTICOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003005, 1000242, '352', 'QUIMICOS P/ MANTENIMIENTO AUTOMOTRIZ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003006, 1000242, '29', 'EQUIPOS AUXILIARES DE MANTENIMIENTO AUTOMOTRIZ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003007, 1000242, '380', 'LLAVES DE BUJIAS, LLAVES DE CRUZ, LLAVES CAMION', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003008, 1000242, '360', 'GRASAS Y LUBRICANTES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003009, 1000242, '998', 'EXHIBIDORES, MATERIAL POP Y RELACIONADOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003010, 1000242, '18', 'LINTERNAS Y PILAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003011, 1000242, '4', 'BIDONES Y EMBUDOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003012, 1000242, '70', 'CAJAS DE HERRAMIENTAS Y ORGANIZADORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003013, 1000242, '2', 'ABRAZADERA DE METAL', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003014, 1000242, '351', 'EXTINTORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003015, 1000242, '349', 'SEGURIDAD VIAL', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003016, 1000242, '258', 'BOTAS DE SEGURIDAD', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003017, 1000242, '370', 'PAPEL AUTOMOTRIZ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003018, 1000242, '265', 'CASCOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003019, 1000242, '267', 'PROTECCION  AUDITIVA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003020, 1000242, '270', 'GUANTES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003021, 1000242, '300', 'SEÑALES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003022, 1000242, '256', 'PROTEC. VISUAL, RESP. SOP. ESPALDA Y ESLINGA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003023, 1000243, '1', 'COMBOS GRUPO 5', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003024, 1000243, '3', 'ACCES. DE BAÑO METALICOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003025, 1000243, '200', 'ACCESORIOS DE BAÑO CERAMICOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003026, 1000243, '203', 'SANITARIOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003027, 1000243, '35', 'FILTROS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003028, 1000243, '60', 'CALENTADORES Y RESISTENCIAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003029, 1000243, '90', 'FREGADEROS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003030, 1000243, '100', 'GABINETES Y ESPEJOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003031, 1000243, '8', 'ASIENTOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003032, 1000243, '998', 'EXHIBIDORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003033, 1000243, '300', 'BLOQUES DE VIDRIO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003034, 1000243, '150', 'SEGURIDAD PARA BAÑOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003035, 1000244, '1', 'COMBOS GRUPO 6', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003036, 1000244, '10', 'BISAGRAS DE TODO TIPO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003037, 1000244, '20', 'CANDADOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003038, 1000244, '29', 'CERRADURAS SEGURIDAD Y CAJAS FUERTES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003039, 1000244, '30', 'CERRADURAS Y CILINDROS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003040, 1000244, '31', 'CERRADURAS GATER', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003041, 1000244, '32', 'CERRADURAS DE POMO Y MANILLA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003042, 1000244, '35', 'BLANCOS DE LLAVE', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003043, 1000244, '40', 'CIERRAPUERTAS PROTECTORES CILINDROS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003044, 1000244, '50', 'CREMALLERAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003045, 1000244, '60', 'SOPORTES PARA CORTINAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003046, 1000244, '70', 'ORGANIZADORES/AEROCLOSET', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003047, 1000244, '90', 'SOPORTES T/ESPAÑOL', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003048, 1000244, '95', 'ACCESORIOS P/PUERTA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003049, 1000244, '120', 'PASADORES P/PUERTAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003050, 1000244, '130', 'ALDABAS/PORTACANDADOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003051, 1000244, '140', 'PIE DE AMIGOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003052, 1000244, '150', 'BUZON PARA CORREO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003053, 1000244, '160', 'CORREDERAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003054, 1000244, '170', 'ROLDANAS, POLEAS Y GARRUCHAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003055, 1000244, '171', 'GARRUCHAS P/PUERTAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003056, 1000244, '200', 'GANCHOS P/COLGAR', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003057, 1000244, '999', 'DEBITOS A CLIENTES 6', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003058, 1000244, '998', 'EXIBIDORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003059, 1000244, '110', 'TUBO CORTINERO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003060, 1000244, '33', 'MANILLAS P/ CERRADURA DE EMBUTIR', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003061, 1000244, '301', 'ACCESORIOS PARA TRABAJOS DE HERRERIA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003062, 1000244, '210', 'TIRADORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003063, 1000245, '1', 'COMBOS VARIOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003064, 1000245, '2', 'ABRAZADERAS, AMARRES Y GRAPAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003065, 1000245, '8', 'CABLES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003066, 1000245, '15', 'ANILLOS Y CONECTORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003067, 1000245, '25', 'BALASTOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003068, 1000245, '38', 'BOMBILLOS BEST VALUE', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003069, 1000245, '40', 'BOMBILLERIA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003070, 1000245, '41', 'LAMPARAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003071, 1000245, '45', 'CABEZOTES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003072, 1000245, '60', 'CAJETINES PARA CONEXIONES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003073, 1000245, '62', 'BARRAS,TERMINALES ELECTRICOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003074, 1000245, '70', 'CUCHILLAS DE PORCELANA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003075, 1000245, '80', 'ENCHUFES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003076, 1000245, '90', 'EXTENSIONES Y REGLETAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003077, 1000245, '110', 'STARTER, RECEPTACULOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003078, 1000245, '130', 'SOCATES VARIOS.', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003079, 1000245, '160', 'TOMACORRIENTES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003080, 1000245, '170', 'BENJAMIN', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003081, 1000245, '171', 'TIMBRES DOMESTICOS.', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003082, 1000245, '180', 'TAPAS P/TOMAS E INTERRUPTORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003083, 1000245, '500', 'BTICINO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003084, 1000245, '501', 'TAPAS GALVANIZADAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003085, 1000245, '502', 'TOMAS Y ENCHUFES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003086, 1000245, '503', 'BREAKERS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003087, 1000245, '504', 'PROTECTORES DE VOLTAJE', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003088, 1000245, '505', 'INTERRUPTORES, DIMMER Y SWITCHES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003089, 1000245, '998', 'EXHIBIDORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003090, 1000245, '5', 'ACCESORIOS DE VIDEO Y AUDIO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003091, 1000245, '550', 'TABLEROS, MEDIDORES Y CAJAS DE DISTRIBUCION', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003092, 1000245, '400', 'SIEMENS INTERRUPTORES Y TOMAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003093, 1000245, '888', 'FLETE', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003094, 1000245, '63', 'GUAYAS Y ACCESORIOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003095, 1000245, '96', 'VENTILADORES Y EXTRACTORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003096, 1000245, '300', 'INTERRUPTORES Y TOMAS ECONOMICAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003097, 1000245, '402', 'EQUIPOS DE CONTROL', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003098, 1000245, '506', 'CONTACTOS Y RELES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003100, 1000246, '30', 'BOYAS Y FLOTANTES PARA TANQUES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003101, 1000246, '31', 'CONEXIONES P/TANQUES DE AGUA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003102, 1000246, '40', 'DESAGUES P/FREGADEROS-LAVAMANOS Y W.C.', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003103, 1000246, '50', 'DUCHAS TELEFONO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003104, 1000246, '60', 'REPUESTOS P/GRIFERIA Y VALVULAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003105, 1000246, '61', 'REPUESTOS PARA SANITARIOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003106, 1000246, '80', 'FLUXOMETROS PARA WC Y URINARIO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003107, 1000246, '120', 'GRIFERIAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003108, 1000246, '140', 'HERRAJES DE WC', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003109, 1000246, '150', 'INODOROS (ALUMINIO-BRONCE)', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003110, 1000246, '170', 'VALVULERIA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003111, 1000246, '180', 'MANGUERAS PARA LAVAMANO Y W.C (CANILLAS)', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003112, 1000246, '218', 'BRAZO P/REGADERA Y CONEXIONES CROMADAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003113, 1000246, '220', 'REGADERAS PARA BAÑO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003114, 1000246, '230', 'REJILLAS P/INODOROS (BRONCE-ALUMINIO-PLASTICAS)', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003115, 1000246, '240', 'SIFONES PARA LAVAMANOS Y FREGADEROS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003116, 1000246, '250', 'SURTIDORES PARA WC', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003117, 1000246, '260', 'TUBOS DE EXTENSION P/FREGADEROS Y LAV.', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003118, 1000246, '280', 'VALVULAS CHECK Y FILTROS P/VALVULA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003119, 1000246, '998', 'EXHIBIDORES Y RELACIONADOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003120, 1000246, '1', 'COMBOS GRIFERIAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003121, 1000246, '190', 'KITS DE INSTALACIÓN PARA SALAS DE BAÑO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003122, 1000247, '1', 'ALAMBRE DE PUAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003123, 1000247, '2', 'ALAMBRE LISO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003124, 1000247, '6', 'AMARRE PARA TECHOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003125, 1000247, '15', 'BARRAS ROSCADAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003126, 1000247, '16', 'TUERCAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003127, 1000247, '17', 'ARANDELAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003128, 1000247, '20', 'CLAVOS EN GENERAL', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003129, 1000247, '22', 'CADENAS GALVANIZADAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003130, 1000247, '30', 'HERRADURAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003131, 1000247, '35', 'ACCS. DE CERCO ELECTRICO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003132, 1000247, '36', 'ENERGIZADOR DE CERCO ELECTRICO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003133, 1000247, '40', 'GANCHOS PARA TECHO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003134, 1000247, '50', 'GRAPAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003135, 1000247, '80', 'MALLA ALFAJOL', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003136, 1000247, '90', 'RAMPLUGS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003137, 1000247, '100', 'MALLA CEDAZO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003138, 1000247, '120', 'MALLA GALLINERO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003139, 1000247, '140', 'MALLAS PAJARERA, POLLITO Y UNIMALLAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003140, 1000247, '160', 'MALLA MOSQUITERO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003141, 1000247, '180', 'MALLA NASA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003143, 1000247, '220', 'MALLA RIPLEX, ESQUINEROS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003144, 1000247, '300', 'TORNILLOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003145, 1000247, '999', 'CARGOS A CLIENTES 4', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003146, 1000247, '998', 'Exhibidores merchandising', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003147, 1000247, '888', 'FLETES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003148, 1000247, '3', 'CONCERTINAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003150, 1000247, '440', 'ESTANTILLO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003151, 1000247, '301', 'TORNILLOS AUTORROSCANTES CATO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003152, 1000248, '1', 'COMBOS GRUPO 9', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003153, 1000248, '4', 'ANGULOS Y PERFILES DE HIERRO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003154, 1000248, '29', 'IMPERMEABILIZANTES Y ASFALTOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003155, 1000248, '30', 'CARTON CHAPAFORTE', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003156, 1000248, '38', 'NIPLES GALVANIZADOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003157, 1000248, '40', 'CONEXIONES GALVANIZADAS  M', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003158, 1000248, '41', 'CONEXIONES PVC Y PLASTICAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003159, 1000248, '51', 'LAMINAS DE ZINC', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003160, 1000248, '60', 'OXIDOS PARA PISO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003161, 1000248, '70', 'CERCHAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003162, 1000248, '80', 'PLETINAS DE HIERRO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003163, 1000248, '100', 'CARRETILLAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003164, 1000248, '105', 'FLEJES PLASTICOS PARA PISO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003165, 1000248, '110', 'ELECTRODOS Y SOLDADURAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003166, 1000248, '115', 'ROMANILLAS Y VENTANAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003167, 1000248, '130', 'TUBOS PARA CERCAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003168, 1000248, '140', 'TUBERIA DE COBRE', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003169, 1000248, '150', 'CONEXIONES TUB. COBRE', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003170, 1000248, '160', 'TUBERIA PULIDA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003171, 1000248, '170', 'TUBOS GALVANIZADOS PARA AGUA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003172, 1000248, '190', 'TUBOS Y CANALES AGUAS BLANCAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003173, 1000248, '200', 'TUBOS ELECTRICIDAD', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003174, 1000248, '210', 'VARILLAS, CABILLAS, ZUNCHOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003175, 1000248, '500', 'TOBO ALBAÑIL', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003176, 1000248, '998', 'EXHIBIDORES Y MATERIAL POP, RELACIONADOS.', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003177, 1000248, '42', 'CONEX GALV GENERICA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003178, 1000248, '888', 'SERVICIO FELTE', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003179, 1000248, '440', 'ACCESORIOS PARA CERCA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003180, 1000248, '101', 'RUEDAS Y TRIPAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003181, 1000248, '102', 'RODAPIES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003182, 1000248, '19', 'PRODUCTOS SIKA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003183, 1000248, '43', 'CONEXIONES CROMADAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003184, 1000248, '44', 'CONEXIONES GALVANIZADAS EN CAJA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003185, 1000248, '290', 'SOPORTES PARA TUBERIA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003186, 1000248, '45', 'PVC ROSCADO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003187, 1000248, '39', 'NIPLES DE PVC', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003273, 1000246, '1', 'COMBOS GRIFERIAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003274, 1000247, '200', 'MALLA PARA PISOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003275, 1000335, '999', 'SIN PARTIDA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003373, 1000239, '106', 'HIDRO LAVADORAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003374, 1000239, '120', 'CEPILLOS DE ALAMBRE                               ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003375, 1000239, '310', 'EXTRACTOR DE TORNILLOS                            ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003376, 1000239, '372', 'PIEDRA P/AMOLAR                                   ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003377, 1000248, '52', 'LAMINAS LIT                                       ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003378, 1000248, '121', 'TUBOS DE CORTINAS                                 ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003379, 1000239, '615', 'REPUESTOS KIT TALADROS B&D                        ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003380, 1000239, '660', 'BURROS P/MECANICOS                                ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003381, 1000239, '900', 'SIN NOMBRE', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003382, 1000241, '13', 'CUCHILLOS                                         ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003383, 1000241, '132', 'TENEDOR P/HENO                                    ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003384, 1000241, '172', 'REGADERAS PARA JARDIN                             ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003385, 1000241, '212', 'BOLAS CRIOLLAS                                    ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003386, 1000241, '225', '225	FULMINANTES PARA CARTUCHOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003387, 1000241, '231', 'MUNICIONES DE PLOMO PARA CARTUCHOS                ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003388, 1000241, '255', 'PROT. VISUAL, RESPIRATORIA, SOP. ESPALDA Y ESLINGA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003389, 1000241, '257', 'MOSQUITERO PARA HAMACA                            ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003390, 1000241, '382', 'LIMPIEZA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003391, 1000240, '23', 'ACCESORIOS P/BOMBAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003392, 1000240, '421', 'WINCHES MINI-MULE Y WINCHE STD.CORONA             ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003475, 1000244, '300', 'PUERTAS Y REJAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003476, 1000244, '400', 'PUERTAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003577, 1000248, '600', 'TANQUE', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003578, 1000242, '50', 'SACOS Y BOLSAS ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003678, 1000245, '42', 'LAMPARAS LED', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003778, 1000241, '392', 'PINTURAS Y ACABADOS QUIMICOLOR', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003879, 1000243, '400', 'AIRES ACONDICIONADOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003880, 1000241, '50', 'SILLAS, BANQUETAS Y MESAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003881, 1000247, '10', 'ARMELLAS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003981, 1000248, '180', 'TUBOS ESTRUCTURALES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1003982, 1000241, '30', 'PLASTICO STRETCH', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004082, 1000240, '50', 'MOTORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004083, 1000243, '401', 'NEVERAS Y CONGELADORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004084, 1000243, '402', 'DISPENSADORES DE AGUA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004183, 1000240, '90', 'REPELENTES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004184, 1000245, '43', 'BOMBILLOS LED ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004185, 1000242, '46', 'PISOS ALTO TRAFICO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004186, 1000243, '450', 'REVESTIMIENTO PARA PAREDES Y PISOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004187, 1000243, '451', 'POR DEFINIR', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004188, 1000239, '700', 'DEMOLEDORES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004189, 1000241, '400', 'REPUESTOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004190, 1000241, '450', 'CAMPING', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004192, 1000239, '9052', 'LÁMINAS DE ACERO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004193, 1000248, '53', 'LÁMINAS DE ACERO ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004194, 1000248, '175', 'TUBOS HIERRO NEGRO PARA HERRERIA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004294, 1000242, '500', 'BICICLETAS Y ACCESORIOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004298, 1000240, '80', 'BEBEDEROS/COMEDEROS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004299, 1000241, '500', 'PRODUCTOS DE LIMPIEZA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004300, 1000241, '600', 'SOLVENTES Y REMOVEDOR', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004301, 1000242, '505', 'PISCINAS Y ACCESORIOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004302, 1000241, '700', 'ACCESORIO DE LIMPIEZA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004303, 1000247, '500', 'REFIRGERANCION COMERCIAL-AUTOMOTRIZ Y ACCESORIOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004304, 1000240, '70', 'ALMACENAMIENTO AGRICOLA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004404, 1000248, '5', 'ANGULOS Y PERFILES DE ALUMINIO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004504, 1000242, '510', 'MESAS DE JUEGO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004505, 1000240, '180', 'MATEROS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004506, 1000242, '257', 'UNIFORMES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004507, 1000248, '54', 'LÁMINAS DE POLIURETANO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004508, 1000240, '170', 'EQUIPOS PARA SIEMBRA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004509, 1000245, '700', 'PROTONIC', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004510, 1000239, '393', 'PINTURAS Y ACABADOS PINECO ', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004610, 1000241, '393', 'PINTURAS Y ACABADOS PINECO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004611, 1000244, '305', 'MOTOR ELECTRICO P/PORTON Y ACCESORIOS', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004612, 1000239, '9', 'ALAMBRE ESMALTADO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004613, 1000245, '9', 'ALAMBRE ESMALTADO', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004614, 1000248, '999', 'FLETES', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004615, 1000241, '550', 'UTENSILIOS DE LIMPIEZA', 'Y')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION, ISACTIVE) values (1004616, 1000242, '71', 'MORRALES, BOLSOS Y LUNCHERAS', 'Y')".replaceAll("\\s+", " ").trim());
    }
}
