package com.smartbuilders.smartsales.ecommerceandroidapp.utils;

import java.util.ArrayList;

/**
 * Created by stein on 4/23/2016.
 */
public class UtilsSubCategory {

    private ArrayList<String> insert;

    public ArrayList<String> getInserts(){
        return insert;
    }

    public UtilsSubCategory(){
        insert = new ArrayList<>();
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002874, 1000239, 'Partida 002', 'ACEITERAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002875, 1000239, 'Partida 010', 'ALICATES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002876, 1000239, 'Partida 012', 'JGO. DE HERRAMIENTAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002877, 1000239, 'Partida 020', 'PROBADORES DE VOLTAJE / MULTITESTER')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002878, 1000239, 'Partida 030', 'AUTOCLETS - RATCHETS - EXTENSIONES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002879, 1000239, 'Partida 050', 'BROCHAS - ACCESORIOS DE PINTURA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002880, 1000239, 'Partida 130', 'CINCELES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002882, 1000239, 'Partida 150', 'CIZALLAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002883, 1000239, 'Partida 180', 'CORTAPORCELANA - CORTATUBO - CORTAVIDRIO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002884, 1000239, 'Partida 190', 'CUCHARAS DE ALBAÑIL')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002885, 1000239, 'Partida 200', 'CUCHILLAS - NAVAJAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002886, 1000239, 'Partida 208', 'DADOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002888, 1000239, 'Partida 230', 'DESTORNILLADORES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002890, 1000239, 'Partida 280', 'MEDICION')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002891, 1000239, 'Partida 290', 'ESMERILES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002892, 1000239, 'Partida 300', 'ESPATULAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002893, 1000239, 'Partida 320', 'KIT P/LATONERO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002894, 1000239, 'Partida 340', 'FORMONES - GUBIAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002895, 1000239, 'Partida 365', 'LIJADORAS - TROMPOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002896, 1000239, 'Partida 370', 'LIMAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002897, 1000239, 'Partida 380', 'LLAVES COMB.- AJUST.- TUBO - ALLEN - CRUZ')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002898, 1000239, 'Partida 410', 'MARTILLOS - MACETAS - MAZOS - MANDARRIAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002899, 1000239, 'Partida 420', 'MECHAS - MACHOS PARA ROSCA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002900, 1000239, 'Partida 430', 'NIVELES Y CALIBRADORES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002901, 1000239, 'Partida 440', 'PALUSTRAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002902, 1000239, 'Partida 450', 'PIQUETAS ALBAÑIL')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002903, 1000239, 'Partida 460', 'COMPRESORES - PISTOLAS - ACCESORIOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002905, 1000239, 'Partida 480', 'PORTA-ELECTRODOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002906, 1000239, 'Partida 485', 'PINZA TIERRA SOLDAR')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002907, 1000239, 'Partida 490', 'PRENSAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002908, 1000239, 'Partida 510', 'REMACHES - REMACHADORAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002910, 1000239, 'Partida 550', 'SALPICADORAS Y REPUESTOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002911, 1000239, 'Partida 560', 'SEGUETAS - SIERRA COPA - HOJAS P/ CALADORA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002912, 1000239, 'Partida 561', 'ARCOS P/SEGUETA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002913, 1000239, 'Partida 570', 'SERRUCHOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002914, 1000239, 'Partida 580', 'TRONZADORAS - INGLETEADORAS - SIERRAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002915, 1000239, 'Partida 590', 'MAQ.SOLDAR - EQUIP.OXICORTE - CAUTIN - ESTAÑO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002916, 1000239, 'Partida 600', 'SOPLETES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002917, 1000239, 'Partida 610', 'TALADROS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002918, 1000239, 'Partida 611', 'MANDRIL - LLAVE MANDRIL - KIT CERRAD.- JGOS.VARIOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002919, 1000239, 'Partida 620', 'TENAZAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002920, 1000239, 'Partida 630', 'TERRAJAS - DADOS PARA TERRAJA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002922, 1000239, 'Partida 650', 'TIRALINEAS - TIZAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002925, 1000239, 'Partida 140', 'CINTA METRICA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002927, 1000240, 'Partida 010', 'BARRAS PARA HOYAR')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002928, 1000240, 'Partida 020', 'BOMBAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002929, 1000240, 'Partida 030', 'DESMALEZADORA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002930, 1000240, 'Partida 040', 'CABOS DE MADERA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002931, 1000240, 'Partida 120', 'CAVADORAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002932, 1000240, 'Partida 140', 'CHICURAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002933, 1000240, 'Partida 160', 'ESCARDILLA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002935, 1000240, 'Partida 220', 'FUMIGADORAS,ROCIADORES SPRAY')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002936, 1000240, 'Partida 260', 'HACHAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002937, 1000240, 'Partida 270', 'CUCHILLA GUADAÑADORA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002938, 1000240, 'Partida 300', 'MACHETES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002939, 1000240, 'Partida 340', 'PALAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002940, 1000240, 'Partida 360', 'PALINES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002941, 1000240, 'Partida 400', 'PICOS (PUNTA Y PALA - GAMELOTEROS)')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002943, 1000240, 'Partida 290', 'CUCHILLOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002945, 1000240, 'Partida 130', 'ESCOBAS DE JARDIN Y RASTRILLOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002946, 1000240, 'Partida 141', 'CONEXIONES Y ACCESORIOS DE RIEGO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002947, 1000240, 'Partida 190', 'TIJERAS PARA JARDIN')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002948, 1000240, 'Partida 150', 'MANGUERAS DE RIEGO Y JARDIN')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002949, 1000240, 'Partida 021', 'HIDRONEUMATICOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002950, 1000240, 'Partida 022', 'MOTOBOMBAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002951, 1000240, 'Partida 031', 'CORTAGRAMA Y SOPLADORA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002952, 1000240, 'Partida 032', 'MOTOSIERRA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002953, 1000240, 'Partida 033', 'ACC. PARA DESM/CORTG/MOTOSIERRA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002954, 1000240, 'Partida 142', 'ACC DE RIEGO PARA JARDIN')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002955, 1000240, 'Partida 019', 'HIDROLAVADORAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002956, 1000240, 'Partida 024', 'GENERADORES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002958, 1000241, 'Partida 001', 'COMBOS GRUPO 2')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002960, 1000241, 'Partida 008', 'CADENAS P/PERROS Y MATEROS, PECHERAS Y COLLARES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002961, 1000241, 'Partida 011', 'COCINAS Y REGULADORES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002963, 1000241, 'Partida 040', 'ESCALERAS D/ALUMINIO TIJERA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002965, 1000241, 'Partida 129', 'CEPILLOS P/BARRER')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002966, 1000241, 'Partida 140', 'MANGUERAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002967, 1000241, 'Partida 205', 'ANZUELOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002968, 1000241, 'Partida 208', 'BALINES PARA FLOWERS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002969, 1000241, 'Partida 233', 'PLOMO EN LAMINA Y DE PESCA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002971, 1000241, 'Partida 236', 'CARRETE PLASTICO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002972, 1000241, 'Partida 320', 'LIJA, ROLLOS, FIBRODISCOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002973, 1000241, 'Partida 324', 'LANA DE ACERO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002974, 1000241, 'Partida 330', 'TIRROS Y CINTAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002975, 1000241, 'Partida 352', 'ACEITE P/ROSCA, SILICONAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002976, 1000241, 'Partida 365', 'PEGA METYLAN Y COLA BLANCA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002977, 1000241, 'Partida 370', 'MASTIQUE Y PASTA PROF.')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002978, 1000241, 'Partida 375', 'PEGAS P/TUBERIAS PVC')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002979, 1000241, 'Partida 380', 'CEMENTOS DE CONTACTO Y CREOLINA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002980, 1000241, 'Partida 385', 'PEGAS EPOXICAS E INSTANTANEAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002981, 1000241, 'Partida 390', 'PINT. SAPOLIN, SPRAY, FONDOS Y MASILLAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002982, 1000241, 'Partida 391', 'PINTURAS Y ACABADOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002983, 1000241, 'Partida 395', 'TEFLONES, CINTAS ELECTRICAS Y DOBLE FAZ')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002984, 1000241, 'Partida 960', 'PESOS, BALANZAS Y BASCULAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002985, 1000241, 'Partida 990', 'TERMOS Y GRIFOS P/TERMOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002987, 1000241, 'Partida 321', 'DISCOS DE CORTE Y DESBASTE')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002988, 1000241, 'Partida 322', 'CEPILLOS DE COPA, CIRCULARES Y DE USO MANUAL')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002993, 1000242, 'Partida 020', 'LAMPARA AUXILIARES, BORNES DE BATERIAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002994, 1000242, 'Partida 030', 'DRIZAS DE NYLON')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002996, 1000242, 'Partida 041', 'ENCERADOS PLASTICOS(ALTA TENACIDAD)')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002997, 1000242, 'Partida 045', 'PLASTICO(TRANSPARENTE Y NEGRO)')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002998, 1000242, 'Partida 060', 'ESTOPAS,TRAPOS Y ALGODON')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1002999, 1000242, 'Partida 080', 'IMPERMEABLES,CORDONES ELAST.')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003000, 1000242, 'Partida 100', 'MECATE (TODO TIPO)')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003001, 1000242, 'Partida 150', 'CARBONES PARA EQUIPOS Y HERRAMIENTAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003002, 1000242, 'Partida 043', 'CINTAS  RATCHET Y GANCHO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003003, 1000242, 'Partida 420', 'SEÑORITAS Y WINCHES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003004, 1000242, 'Partida 350', 'GATOS DE BOTELLA, GATOS CAIMAN, GATO PARA RUSTICOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003005, 1000242, 'Partida 352', 'QUIMICOS P/ MANTENIMIENTO AUTOMOTRIZ')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003006, 1000242, 'Partida 029', 'EQUIPOS AUXILIARES DE MANTENIMIENTO AUTOMOTRIZ')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003007, 1000242, 'Partida 380', 'LLAVES DE BUJIAS, LLAVES DE CRUZ, LLAVES CAMION')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003009, 1000242, 'Partida 998', 'EXHIBIDORES, MATERIAL POP Y RELACIONADOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003010, 1000242, 'Partida 018', 'LINTERNAS Y PILAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003011, 1000242, 'Partida 004', 'BIDONES Y EMBUDOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003012, 1000242, 'Partida 070', 'CAJAS DE HERRAMIENTAS Y ORGANIZADORES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003013, 1000242, 'Partida 002', 'ABRAZADERA DE METAL')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003014, 1000242, 'Partida 351', 'EXTINTORES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003015, 1000242, 'Partida 349', 'SEGURIDAD VIAL')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003016, 1000242, 'Partida 258', 'BOTAS DE SEGURIDAD')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003018, 1000242, 'Partida 265', 'CASCOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003019, 1000242, 'Partida 267', 'PROTECCION  AUDITIVA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003020, 1000242, 'Partida 270', 'GUANTES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003021, 1000242, 'Partida 300', 'SEÑALES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003022, 1000242, 'Partida 256', 'PROTEC. VISUAL, RESP. SOP. ESPALDA Y ESLINGA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003023, 1000243, 'Partida 001', 'COMBOS GRUPO 5')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003024, 1000243, 'Partida 003', 'ACCES. DE BAÑO METALICOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003025, 1000243, 'Partida 200', 'ACCESORIOS DE BAÑO CERAMICOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003026, 1000243, 'Partida 203', 'SANITARIOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003027, 1000243, 'Partida 035', 'FILTROS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003028, 1000243, 'Partida 060', 'CALENTADORES Y RESISTENCIAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003029, 1000243, 'Partida 090', 'FREGADEROS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003030, 1000243, 'Partida 100', 'GABINETES Y ESPEJOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003031, 1000243, 'Partida 008', 'ASIENTOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003033, 1000243, 'Partida 300', 'BLOQUES DE VIDRIO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003036, 1000244, 'Partida 010', 'BISAGRAS DE TODO TIPO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003037, 1000244, 'Partida 020', 'CANDADOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003039, 1000244, 'Partida 030', 'CERRADURAS Y CILINDROS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003040, 1000244, 'Partida 031', 'CERRADURAS GATER')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003041, 1000244, 'Partida 032', 'CERRADURAS DE POMO Y MANILLA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003042, 1000244, 'Partida 035', 'BLANCOS DE LLAVE')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003043, 1000244, 'Partida 040', 'CIERRAPUERTAS PROTECTORES CILINDROS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003044, 1000244, 'Partida 050', 'CREMALLERAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003045, 1000244, 'Partida 060', 'SOPORTES PARA CORTINAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003046, 1000244, 'Partida 070', 'ORGANIZADORES/AEROCLOSET')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003048, 1000244, 'Partida 095', 'ACCESORIOS P/PUERTA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003049, 1000244, 'Partida 120', 'PASADORES P/PUERTAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003050, 1000244, 'Partida 130', 'ALDABAS/PORTACANDADOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003051, 1000244, 'Partida 140', 'PIE DE AMIGOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003052, 1000244, 'Partida 150', 'BUZON PARA CORREO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003053, 1000244, 'Partida 160', 'CORREDERAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003054, 1000244, 'Partida 170', 'ROLDANAS, POLEAS Y GARRUCHAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003056, 1000244, 'Partida 200', 'GANCHOS P/COLGAR')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003059, 1000244, 'Partida 110', 'TUBO CORTINERO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003060, 1000244, 'Partida 033', 'MANILLAS P/ CERRADURA DE EMBUTIR')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003061, 1000244, 'Partida 301', 'ACCESORIOS PARA TRABAJOS DE HERRERIA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003062, 1000244, 'Partida 210', 'TIRADORES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003064, 1000245, 'Partida 002', 'ABRAZADERAS, AMARRES Y GRAPAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003065, 1000245, 'Partida 008', 'CABLES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003066, 1000245, 'Partida 015', 'ANILLOS Y CONECTORES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003067, 1000245, 'Partida 025', 'BALASTOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003068, 1000245, 'Partida 038', 'BOMBILLOS BEST VALUE')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003069, 1000245, 'Partida 040', 'BOMBILLERIA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003070, 1000245, 'Partida 041', 'LAMPARAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003072, 1000245, 'Partida 060', 'CAJETINES PARA CONEXIONES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003073, 1000245, 'Partida 062', 'BARRAS,TERMINALES ELECTRICOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003074, 1000245, 'Partida 070', 'CUCHILLAS DE PORCELANA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003076, 1000245, 'Partida 090', 'EXTENSIONES Y REGLETAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003077, 1000245, 'Partida 110', 'STARTER, RECEPTACULOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003078, 1000245, 'Partida 130', 'SOCATES VARIOS.')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003081, 1000245, 'Partida 171', 'TIMBRES DOMESTICOS.')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003083, 1000245, 'Partida 500', 'BTICINO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003084, 1000245, 'Partida 501', 'TAPAS GALVANIZADAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003085, 1000245, 'Partida 502', 'TOMAS Y ENCHUFES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003086, 1000245, 'Partida 503', 'BREAKERS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003087, 1000245, 'Partida 504', 'PROTECTORES DE VOLTAJE')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003090, 1000245, 'Partida 005', 'ACCESORIOS DE VIDEO Y AUDIO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003091, 1000245, 'Partida 550', 'TABLEROS, MEDIDORES Y CAJAS DE DISTRIBUCION')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003092, 1000245, 'Partida 400', 'SIEMENS INTERRUPTORES Y TOMAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003094, 1000245, 'Partida 063', 'GUAYAS Y ACCESORIOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003096, 1000245, 'Partida 300', 'INTERRUPTORES Y TOMAS ECONOMICAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003100, 1000246, 'Partida 030', 'BOYAS Y FLOTANTES PARA TANQUES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003101, 1000246, 'Partida 031', 'CONEXIONES P/TANQUES DE AGUA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003102, 1000246, 'Partida 040', 'DESAGUES P/FREGADEROS-LAVAMANOS Y W.C.')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003103, 1000246, 'Partida 050', 'DUCHAS TELEFONO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003104, 1000246, 'Partida 060', 'REPUESTOS P/GRIFERIA Y VALVULAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003105, 1000246, 'Partida 061', 'REPUESTOS PARA SANITARIOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003106, 1000246, 'Partida 080', 'FLUXOMETROS PARA WC Y URINARIO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003107, 1000246, 'Partida 120', 'GRIFERIAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003108, 1000246, 'Partida 140', 'HERRAJES DE WC')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003109, 1000246, 'Partida 150', 'INODOROS (ALUMINIO-BRONCE)')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003110, 1000246, 'Partida 170', 'VALVULERIA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003111, 1000246, 'Partida 180', 'MANGUERAS PARA LAVAMANO Y W.C (CANILLAS)')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003112, 1000246, 'Partida 218', 'BRAZO P/REGADERA Y CONEXIONES CROMADAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003113, 1000246, 'Partida 220', 'REGADERAS PARA BAÑO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003114, 1000246, 'Partida 230', 'REJILLAS P/INODOROS (BRONCE-ALUMINIO-PLASTICAS)')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003115, 1000246, 'Partida 240', 'SIFONES PARA LAVAMANOS Y FREGADEROS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003116, 1000246, 'Partida 250', 'SURTIDORES PARA WC')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003117, 1000246, 'Partida 260', 'TUBOS DE EXTENSION P/FREGADEROS Y LAV.')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003118, 1000246, 'Partida 280', 'VALVULAS CHECK Y FILTROS P/VALVULA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003121, 1000246, 'Partida 190', 'KITS DE INSTALACIÓN PARA SALAS DE BAÑO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003123, 1000247, 'Partida 002', 'ALAMBRE LISO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003124, 1000247, 'Partida 006', 'AMARRE PARA TECHOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003125, 1000247, 'Partida 015', 'BARRAS ROSCADAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003127, 1000247, 'Partida 017', 'ARANDELAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003128, 1000247, 'Partida 020', 'CLAVOS EN GENERAL')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003129, 1000247, 'Partida 022', 'CADENAS GALVANIZADAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003130, 1000247, 'Partida 030', 'HERRADURAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003131, 1000247, 'Partida 035', 'ACCS. DE CERCO ELECTRICO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003132, 1000247, 'Partida 036', 'ENERGIZADOR DE CERCO ELECTRICO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003136, 1000247, 'Partida 090', 'RAMPLUGS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003137, 1000247, 'Partida 100', 'MALLA CEDAZO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003138, 1000247, 'Partida 120', 'MALLA GALLINERO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003139, 1000247, 'Partida 140', 'MALLAS PAJARERA, POLLITO Y UNIMALLAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003140, 1000247, 'Partida 160', 'MALLA MOSQUITERO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003141, 1000247, 'Partida 180', 'MALLA NASA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003143, 1000247, 'Partida 220', 'MALLA RIPLEX, ESQUINEROS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003144, 1000247, 'Partida 300', 'TORNILLOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003150, 1000247, 'Partida 440', 'ESTANTILLO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003151, 1000247, 'Partida 301', 'TORNILLOS AUTORROSCANTES CATO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003152, 1000248, 'Partida 001', 'COMBOS GRUPO 9')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003153, 1000248, 'Partida 004', 'ANGULOS Y PERFILES DE HIERRO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003154, 1000248, 'Partida 029', 'IMPERMEABILIZANTES Y ASFALTOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003156, 1000248, 'Partida 038', 'NIPLES GALVANIZADOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003157, 1000248, 'Partida 040', 'CONEXIONES GALVANIZADAS  M')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003158, 1000248, 'Partida 041', 'CONEXIONES PVC Y PLASTICAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003159, 1000248, 'Partida 051', 'LAMINAS DE ZINC')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003160, 1000248, 'Partida 060', 'OXIDOS PARA PISO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003162, 1000248, 'Partida 080', 'PLETINAS DE HIERRO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003163, 1000248, 'Partida 100', 'CARRETILLAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003164, 1000248, 'Partida 105', 'FLEJES PLASTICOS PARA PISO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003165, 1000248, 'Partida 110', 'ELECTRODOS Y SOLDADURAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003166, 1000248, 'Partida 115', 'ROMANILLAS Y VENTANAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003168, 1000248, 'Partida 140', 'TUBERIA DE COBRE')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003169, 1000248, 'Partida 150', 'CONEXIONES TUB. COBRE')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003170, 1000248, 'Partida 160', 'TUBERIA PULIDA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003171, 1000248, 'Partida 170', 'TUBOS GALVANIZADOS PARA AGUA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003172, 1000248, 'Partida 190', 'TUBOS Y CANALES AGUAS BLANCAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003173, 1000248, 'Partida 200', 'TUBOS ELECTRICIDAD')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003174, 1000248, 'Partida 210', 'VARILLAS, CABILLAS, ZUNCHOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003175, 1000248, 'Partida 500', 'TOBO ALBAÑIL')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003179, 1000248, 'Partida 440', 'ACCESORIOS PARA CERCA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003180, 1000248, 'Partida 101', 'RUEDAS Y TRIPAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003181, 1000248, 'Partida 102', 'RODAPIES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003182, 1000248, 'Partida 019', 'PRODUCTOS SIKA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003183, 1000248, 'Partida 043', 'CONEXIONES CROMADAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003184, 1000248, 'Partida 044', 'CONEXIONES GALVANIZADAS EN CAJA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003185, 1000248, 'Partida 290', 'SOPORTES PARA TUBERIA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003187, 1000248, 'Partida 039', 'NIPLES DE PVC')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003274, 1000247, 'Partida 200', 'MALLA PARA PISOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003476, 1000244, 'Partida 400', 'PUERTAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003577, 1000248, 'Partida 600', 'TANQUE')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003578, 1000242, 'Partida 050', 'SACOS Y BOLSAS ')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003678, 1000245, 'Partida 042', 'LAMPARAS LED')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003778, 1000241, 'Partida 392', 'PINTURAS Y ACABADOS QUIMICOLOR')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003880, 1000241, 'Partida 050', 'SILLAS, BANQUETAS Y MESAS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1003981, 1000248, 'Partida 180', 'TUBOS ESTRUCTURALES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004082, 1000240, 'Partida 050', 'MOTORES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004084, 1000243, 'Partida 402', 'DISPENSADORES DE AGUA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004184, 1000245, 'Partida 043', 'BOMBILLOS LED ')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004186, 1000243, 'Partida 450', 'REVESTIMIENTO PARA PAREDES Y PISOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004187, 1000243, 'Partida 451', 'POR DEFINIR')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004188, 1000239, 'Partida 700', 'DEMOLEDORES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004193, 1000248, 'Partida 053', 'LÁMINAS DE ACERO ')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004194, 1000248, 'Partida 175', 'TUBOS HIERRO NEGRO PARA HERRERIA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004298, 1000240, 'Partida 080', 'BEBEDEROS/COMEDEROS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004299, 1000241, 'Partida 500', 'PRODUCTOS DE LIMPIEZA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004300, 1000241, 'Partida 600', 'SOLVENTES Y REMOVEDOR')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004302, 1000241, 'Partida 700', 'ACCESORIO DE LIMPIEZA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004303, 1000247, 'Partida 500', 'REFIRGERANCION COMERCIAL-AUTOMOTRIZ Y ACCESORIOS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004304, 1000240, 'Partida 070', 'ALMACENAMIENTO AGRICOLA')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004404, 1000248, 'Partida 005', 'ANGULOS Y PERFILES DE ALUMINIO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004504, 1000242, 'Partida 510', 'MESAS DE JUEGO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004505, 1000240, 'Partida 180', 'MATEROS')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004506, 1000242, 'Partida 257', 'UNIFORMES')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004610, 1000241, 'Partida 393', 'PINTURAS Y ACABADOS PINECO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004613, 1000245, 'Partida 009', 'ALAMBRE ESMALTADO')".replaceAll("\\s+", " ").trim());
        insert.add("insert into SUBCATEGORY (SUBCATEGORY_ID, CATEGORY_ID, NAME, DESCRIPTION) values  (1004615, 1000241, 'Partida 550', 'UTENSILIOS DE LIMPIEZA')".replaceAll("\\s+", " ").trim());
    }
}
